---
title: "Introduction to bioinformatics"
author: "Laurent Gatto"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
knit: bookdown::preview_chapter
description: "Course material for the Introduction to bioinformatics (WSBIM1207) course at UCLouvain."
output:
  msmbstyle::msmb_html_book:
    toc: TRUE
    toc_depth: 1
    split_by: chapter
    split_bib: no
    margin_references: TRUE
link-citations: yes
bibliography: [refs.bib, packages.bib]
---

# Preamble {-}

### Course information {-}

- Language: course material in English, course taught in French
- Thursday mornings, 8.30 - 12.30
- From 7 Februray to 4 April 2019
- [Course page](https://uclouvain.be/cours-2018-wsbim1207.html) (in French)
- Teaching assistant: Kevin Missault

### Thèmes abordés {-}

Ce cours introductif à la bioinformatique et sciences des données
appliquées aux sciences biomédicales introduira les méthodologies et
technologies utilisées en bioinformatique. Les étudiants apprendront
comment gérer un projets bioinformatique et comment manipuler et
visualiser des jeux de données de tailles moyennes.

### Acquis d'apprentissage {-}

A l'issue de ce cours, les étudiants auront une comprehension que ce
qu'est la bioinformatique et quand la bioinformatique leur sera
requise. Ils seront également en mesure de

1. Analyser un problème bioinformatique simple, proposer une solution
   informatique pour le résoudre et la mettre en oeuvre.
2. Décomposer un problème simple en sous-problèmes et les résoudre
   sous forme de scripts d'analyse.
3. Lire et comprendre des scripts d'analyse existants.
4. Utiliser des outils informatiques de support à la programmation.
5. Exploiter la documentation technique du langage informatique R et
   des vignettes Bioconductor.
6. Réaliser des scripts R et rapports d'analyse de petite taille en Rmd.

Eu égards de référentiel des acquis d'apprentissage du programme de
bachelier en sciences biomédicales, ce cours contribue au
développement, à l'acquisition et a l'évaluation des acquis suivants:
2a, 2c, 3c, 5a, 5b, 5c, 5d.

### Méthodes d'enseignement {-}

Le cours sera dispensé sous forme de travaux pratiques, au cours
desquels les étudiants seront amenés à réaliser des exercices de
programmation suivant des problèmes concrets rencontrés en sciences
biomédicales, en utilisant le langage de programmation R et
l'environnement de programmation RStudio.

La présence des étudiants à l'ensemble des cours (volumes 1 et 2) est
obligatoire. Les présences seront comptabilisées. En case de trois
absences non justifiées, l'étudiant(e) pourra se voir refuser la
participation à l'examen de fin de cours.

### Mode d'évaluation {-}

L'évaluation se fera sur ordinateur; les étudiants prépareront un
rapport reproductible en Rmd sous RStudio, répondant à des exercices
et préparant des analyses de petites taille tels que présentés et
pratiqués durant le cours.

### Contenu {-}

Ce cours introductif à la bioinformatique abordera les thèmes suivants:

- Qu'est ce que la bioinformatique et quelles sont ses domaines d'applications.
- Technologies and méthodologies utilisées en bioinformatique
- Introduction aux technologies et données omiques.
- Bases de données biologiques et données publiques.
- Formats et fichiers en bioinformatique.

Dans sa partie sciences de données appliquées aux sciences
biomédicales, les thèmes suivants seront abordés:

- Gestion de projet d'analyse de données et recherche reproductible.
- Organisation de données dans des tableurs.
- Utilisation de l'environnement de programmation [RStudio](https://www.rstudio.com/).
- Notions pratiques d'analyse de données et de programmation sous en [R](https://www.r-project.org/).
- Introduction aux structures de données élémentaires sous R.
- Manipulation et visualisation de données.
- Analyses et structures de données haut-débit avec R et [Bioconductor](https://bioconductor.org/).
- Introduction aux bases des données relationnelles et SQL (structured query language).


```{r include=FALSE}
# automatically create a bib database for R packages
knitr::write_bib(c(
  .packages(), 'bookdown', 'knitr', 'rmarkdown'
), 'packages.bib')
```
