<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

<meta charset="utf-8" />
<meta name="generator" content="pandoc" />
<meta name="viewport" content="width=device-width, initial-scale=1" />
<meta property="og:title" content="Chapter 5 Manipulating and analyzing data with dplyr | Introduction to bioinformatics" />
<meta property="og:type" content="book" />


<meta property="og:description" content="Course material for the Introduction to bioinformatics (WSBIM1207) course at UCLouvain." />


<meta name="author" content="Laurent Gatto" />

<meta name="date" content="2021-03-21" />

<script type="text/x-mathjax-config">
MathJax.Hub.Config({
  TeX: { equationNumbers: { autoNumber: "AMS" } }
});
</script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<meta name="description" content="Course material for the Introduction to bioinformatics (WSBIM1207) course at UCLouvain.">

<title>Chapter 5 Manipulating and analyzing data with dplyr | Introduction to bioinformatics</title>

<script src="libs/header-attrs-2.7/header-attrs.js"></script>
<link href="libs/tufte-css-2015.12.29/tufte.css" rel="stylesheet" />
<link href="libs/tufte-css-2015.12.29/envisioned.css" rel="stylesheet" />
<link href="libs/msmb-css-0/msmb.css" rel="stylesheet" />
<script>
function toggle_visibility(id1, id2) {
var e = document.getElementById(id1);
var f = document.getElementById(id2);

e.style.display = ((e.style.display!='none') ? 'none' : 'block');

if(f.classList.contains('fa-plus-square')) {
    f.classList.add('fa-minus-square')
    f.classList.remove('fa-plus-square')
} else {
    f.classList.add('fa-plus-square')
    f.classList.remove('fa-minus-square')
}

}
</script>
<script>
function copy_link(id) {
  var dummy = document.createElement('input'),
  text = window.location.href.split(/[?#]/)[0] + '#' + id;
  document.body.appendChild(dummy);
  dummy.value = text;
  dummy.select();
  document.execCommand('copy');
  document.body.removeChild(dummy);
  
  var tooltip = document.getElementById(id + '-tooltip');
  tooltip.innerHTML = 'Copied!';
}

function reset_tooltip(id) {
  var tooltip = document.getElementById(id);
  tooltip.innerHTML = 'Copy link';
}
</script>
<script src="libs/htmlwidgets-1.5.3/htmlwidgets.js"></script>
<script src="libs/jquery-3.5.1/jquery.min.js"></script>
<link href="libs/datatables-css-0.0.0/datatables-crosstalk.css" rel="stylesheet" />
<script src="libs/datatables-binding-0.17/datatables.js"></script>
<link href="libs/dt-core-1.10.20/css/jquery.dataTables.min.css" rel="stylesheet" />
<link href="libs/dt-core-1.10.20/css/jquery.dataTables.extra.css" rel="stylesheet" />
<script src="libs/dt-core-1.10.20/js/jquery.dataTables.min.js"></script>
<link href="libs/crosstalk-1.1.1/css/crosstalk.css" rel="stylesheet" />
<script src="libs/crosstalk-1.1.1/js/crosstalk.min.js"></script>


<style type="text/css">code{white-space: pre;}</style>
<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }

code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<style type="text/css">
/* Used with Pandoc 2.11+ new --citeproc when CSL is used */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}
</style>

<link rel="stylesheet" href="style.css" type="text/css" />

</head>

<body>



<div class="row">
<div class="col-sm-12">
<div id="TOC">
<ul class="navbar">
<li class="msmb"><p class="title">Introduction to bioinformatics<p><p class="author">Laurent Gatto</p>
<li class="dropdown" style="float:right">
<a href="javascript:void(0)" class="dropbtn">&#x25BE; Chapters</a>
<div class="dropdown-content">
<a href="index.html">Preamble</a>
<a href="sec-dataorg.html"><span class="toc-section-number">1</span> Data organisation with Spreadsheets</a>
<a href="sec-rrstudio.html"><span class="toc-section-number">2</span> R and RStudio</a>
<a href="sec-startr.html"><span class="toc-section-number">3</span> Introduction to R</a>
<a href="sec-startdata.html"><span class="toc-section-number">4</span> Starting with data</a>
<a id="active-page" href="sec-dplyr.html"><span class="toc-section-number">5</span> Manipulating and analyzing data with dplyr</a><ul class="toc-sections">
<li class="toc"><a href="#data-manipulation-using-dplyr-and-tidyr"> Data Manipulation using <strong><code>dplyr</code></strong> and <strong><code>tidyr</code></strong></a></li>
<li class="toc"><a href="#what-are-dplyr-and-tidyr"> What are <strong><code>dplyr</code></strong> and <strong><code>tidyr</code></strong>?</a></li>
<li class="toc"><a href="#selecting-columns-and-filtering-rows"> Selecting columns and filtering rows</a></li>
<li class="toc"><a href="#pipes"> Pipes</a></li>
<li class="toc"><a href="#mutate"> Mutate</a></li>
<li class="toc"><a href="#split-apply-combine-data-analysis"> Split-apply-combine data analysis</a></li>
<li class="toc"><a href="#reshaping-data"> Reshaping data</a></li>
<li class="toc"><a href="#exporting-data-1"> Exporting data</a></li>
<li class="toc"><a href="#additional-exercises-3"> Additional exercises</a></li>
</ul>
<a href="sec-vis.html"><span class="toc-section-number">6</span> Data visualization</a>
<a href="sec-join.html"><span class="toc-section-number">7</span> Joining tables</a>
<a href="sec-rr.html"><span class="toc-section-number">8</span> Reproducible research</a>
<a href="sec-bioinfo.html"><span class="toc-section-number">9</span> Bioinformatics</a>
<a href="sec-prog.html"><span class="toc-section-number">10</span> Additional programming concepts</a>
<a href="sec-ccl.html"><span class="toc-section-number">11</span> Conclusions</a>
<a href="sec-anx.html"><span class="toc-section-number">12</span> Annex</a>
<a href="session-information.html"><span class="toc-section-number">13</span> Session information</a>
</div>
</li>
</ul>
</div>
</div>
</div>
<div class="row">
<div class="col-sm-12">
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN" "http://www.w3.org/TR/REC-html40/loose.dtd">
<html><body><div id="sec:dplyr" class="section level1" number="5">
<h1>
<span class="header-section-number">Chapter 5</span> Manipulating and analyzing data with dplyr</h1>
<p><strong>Learning Objectives</strong></p>
<ul>
<li><p>Describe the purpose of the <strong><code>dplyr</code></strong> and <strong><code>tidyr</code></strong> packages.</p></li>
<li><p>Select certain columns in a data frame with the <strong><code>dplyr</code></strong> function
<code>select</code>.</p></li>
<li><p>Select certain rows in a data frame according to filtering
conditions with the <strong><code>dplyr</code></strong> function <code>filter</code> .</p></li>
<li><p>Link the output of one <strong><code>dplyr</code></strong> function to the input of another
function with the ‘pipe’ operator <code>%&gt;%</code>.</p></li>
<li><p>Add new columns to a data frame that are functions of existing
columns with <code>mutate</code>.</p></li>
<li><p>Use the split-apply-combine concept for data analysis.</p></li>
<li><p>Use <code>summarize</code>, <code>group_by</code>, and <code>count</code> to split a data frame into
groups of observations, apply summary statistics for each group, and
then combine the results.</p></li>
<li><p>Describe the concept of a wide and a long table format and for which
purpose those formats are useful.</p></li>
<li><p>Reshape a data frame from long to wide format and back with the
<code>pivot_wider()</code> and <code>pivot_longer()</code> commands from the
<strong><code>tidyr</code></strong> package.</p></li>
</ul>
<div id="data-manipulation-using-dplyr-and-tidyr" class="section level2" number="5.1">
<h2>
<span class="header-section-number">5.1</span> Data Manipulation using <strong><code>dplyr</code></strong> and <strong><code>tidyr</code></strong>
<div class="tooltip"><button class="internal-link-btn" onclick="copy_link('data-manipulation-using-dplyr-and-tidyr')" onmouseout="reset_tooltip('data-manipulation-using-dplyr-and-tidyr-tooltip')"><span class="tooltiptext" id="data-manipulation-using-dplyr-and-tidyr-tooltip">Copy link</span><i class="fa fa-link"></i></button></div>
</h2>
<p>Bracket subsetting is handy, but it can be cumbersome and difficult to
read, especially for complicated operations. Enter
<strong><code>dplyr</code></strong>. <strong><code>dplyr</code></strong> is a package for making tabular data
manipulation easier. It pairs nicely with <strong><code>tidyr</code></strong> which enables
you to swiftly convert between different data formats for plotting and
analysis.</p>
<p>Packages in R are basically sets of additional functions that let you
do more stuff. The functions we’ve been using so far, like <code>str()</code> or
<code>data.frame()</code>, come built into R; packages give you access to more of
them. Before you use a package for the first time you need to install
it on your machine, and then you should import it in every subsequent
R session when you need it. You should already have installed the
<strong><code>tidyverse</code></strong> package. This is an “umbrella-package” that installs
several packages useful for data analysis which work together well
such as <strong><code>tidyr</code></strong>, <strong><code>dplyr</code></strong>, <strong><code>ggplot2</code></strong>, <strong><code>tibble</code></strong>, etc.</p>
<p>The <strong><code>tidyverse</code></strong> package tries to address 3 common issues that
arise when doing data analysis with some of functions that come with
R:</p>
<ol style="list-style-type: decimal">
<li>The results from a base R function sometimes depend on the type of data.</li>
<li>Using R expressions in a non standard way, which can be confusing for new
learners.</li>
<li>Hidden arguments, having default operations that new learners are not aware
of.</li>
</ol>
<p>We have seen in our previous lesson that when building or importing a
data frame, the columns that contain characters (i.e., text) are
coerced (=converted) into the <code>factor</code> data type. We had to set
<strong><code>stringsAsFactors</code></strong> to <strong><code>FALSE</code></strong> to avoid this hidden argument to
convert our data type.</p>
<p>This time will use the <strong><code>tidyverse</code></strong> package to read the data and
avoid having to set <strong><code>stringsAsFactors</code></strong> to <strong><code>FALSE</code></strong></p>
<p>To load the package type:</p>
<div class="sourceCode" id="cb276"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb276-1"><a href="sec-dplyr.html#cb276-1" aria-hidden="true" tabindex="-1"></a><span class="do">## load the tidyverse packages, incl. dplyr</span></span>
<span id="cb276-2"><a href="sec-dplyr.html#cb276-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(<span class="st">"tidyverse"</span>)</span></code></pre></div>
<p>The <a href="https://github.com/rstudio/cheatsheets/raw/master/data-transformation.pdf">Data Transformation Cheat
Sheet</a>
provides an overview of the <code>dplyr</code> grammar, offering more details and
functions that we will see in this chapter.</p>
</div>
<div id="what-are-dplyr-and-tidyr" class="section level2" number="5.2">
<h2>
<span class="header-section-number">5.2</span> What are <strong><code>dplyr</code></strong> and <strong><code>tidyr</code></strong>?<div class="tooltip"><button class="internal-link-btn" onclick="copy_link('what-are-dplyr-and-tidyr')" onmouseout="reset_tooltip('what-are-dplyr-and-tidyr-tooltip')"><span class="tooltiptext" id="what-are-dplyr-and-tidyr-tooltip">Copy link</span><i class="fa fa-link"></i></button></div>
</h2>
<p>The package <strong><code>dplyr</code></strong> provides easy tools for the most common data manipulation
tasks. It is built to work directly with data frames, with many common tasks
optimized by being written in a compiled language (C++). An additional feature is the
ability to work directly with data stored in an external database. The benefits of
doing this are that the data can be managed natively in a relational database,
queries can be conducted on that database, and only the results of the query are
returned.</p>
<p>This addresses a common problem with R in that all operations are conducted
in-memory and thus the amount of data you can work with is limited by available
memory. The database connections essentially remove that limitation in that you
can connect to a database of many hundreds of GB, conduct queries on it directly, and pull
back into R only what you need for analysis.</p>
<p>The package <strong><code>tidyr</code></strong> addresses the common problem of wanting to
reshape your data for plotting and use by different R
functions. Sometimes we want data sets where we have one row per
measurement. Sometimes we want a data frame where each measurement
type has its own column, and rows are instead more aggregated groups -
like plots or aquaria. Moving back and forth between these formats is
nontrivial, and <strong><code>tidyr</code></strong> gives you tools for this and more
sophisticated data manipulation.</p>
<p>To learn more about <strong><code>dplyr</code></strong> and <strong><code>tidyr</code></strong> after the workshop,
you may want to check out this <a href="https://github.com/rstudio/cheatsheets/raw/master/data-transformation.pdf">handy data transformation with
<strong><code>dplyr</code></strong>
cheatsheet</a>
and this <a href="https://github.com/rstudio/cheatsheets/raw/master/data-import.pdf">one about
<strong><code>tidyr</code></strong></a>.</p>
<p>We’ll read in our data using the <code>read_csv()</code> function, from the
tidyverse package <strong><code>readr</code></strong>, instead of <code>read.csv()</code>.</p>
<div class="sourceCode" id="cb277"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb277-1"><a href="sec-dplyr.html#cb277-1" aria-hidden="true" tabindex="-1"></a>surveys <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"data/portal_data_joined.csv"</span>)</span></code></pre></div>
<pre><code>## 
## ── Column specification ───────────────────────────────────────────────────────────────────────────────────────────────────────────────
## cols(
##   record_id = col_double(),
##   month = col_double(),
##   day = col_double(),
##   year = col_double(),
##   plot_id = col_double(),
##   species_id = col_character(),
##   sex = col_character(),
##   hindfoot_length = col_double(),
##   weight = col_double(),
##   genus = col_character(),
##   species = col_character(),
##   taxa = col_character(),
##   plot_type = col_character()
## )</code></pre>
<div class="sourceCode" id="cb279"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb279-1"><a href="sec-dplyr.html#cb279-1" aria-hidden="true" tabindex="-1"></a><span class="do">## inspect the data</span></span>
<span id="cb279-2"><a href="sec-dplyr.html#cb279-2" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(surveys)</span>
<span id="cb279-3"><a href="sec-dplyr.html#cb279-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb279-4"><a href="sec-dplyr.html#cb279-4" aria-hidden="true" tabindex="-1"></a><span class="do">## preview the data</span></span>
<span id="cb279-5"><a href="sec-dplyr.html#cb279-5" aria-hidden="true" tabindex="-1"></a><span class="co"># View(surveys)</span></span></code></pre></div>
<p>Notice that the class of the data is now <code>tbl_df</code></p>
<p>This is referred to as a “tibble.” Tibbles tweak some of the behaviors
of the data frame objects we introduced in the previous episode. The
data structure is very similar to a data frame. For our purposes the
only differences are that:</p>
<ol style="list-style-type: decimal">
<li>In addition to displaying the data type of each column under its name, it
only prints the first few rows of data and only as many columns as fit on one
screen.</li>
<li>Columns of class <code>character</code> are never converted into factors.</li>
</ol>
<p>We’re going to learn some of the most common <strong><code>dplyr</code></strong> functions:</p>
<ul>
<li>
<code>select()</code>: subset columns</li>
<li>
<code>filter()</code>: subset rows on conditions</li>
<li>
<code>mutate()</code>: create new columns by using information from other columns</li>
<li>
<code>group_by()</code> and <code>summarize()</code>: create summary statisitcs on grouped data</li>
<li>
<code>arrange()</code>: sort results</li>
<li>
<code>count()</code>: count discrete values</li>
</ul>
</div>
<div id="selecting-columns-and-filtering-rows" class="section level2" number="5.3">
<h2>
<span class="header-section-number">5.3</span> Selecting columns and filtering rows<div class="tooltip"><button class="internal-link-btn" onclick="copy_link('selecting-columns-and-filtering-rows')" onmouseout="reset_tooltip('selecting-columns-and-filtering-rows-tooltip')"><span class="tooltiptext" id="selecting-columns-and-filtering-rows-tooltip">Copy link</span><i class="fa fa-link"></i></button></div>
</h2>
<p>To select columns of a data frame, use <code>select()</code>. The first argument
to this function is the data frame (<code>surveys</code>), and the subsequent
arguments are the columns to keep.</p>
<div class="sourceCode" id="cb280"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb280-1"><a href="sec-dplyr.html#cb280-1" aria-hidden="true" tabindex="-1"></a><span class="fu">select</span>(surveys, plot_id, species_id, weight)</span></code></pre></div>
<p>To select all columns <em>except</em> certain ones, put a “-” in front of
the variable to exclude it.</p>
<div class="sourceCode" id="cb281"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb281-1"><a href="sec-dplyr.html#cb281-1" aria-hidden="true" tabindex="-1"></a><span class="fu">select</span>(surveys, <span class="sc">-</span>record_id, <span class="sc">-</span>species_id)</span></code></pre></div>
<p>This will select all the variables in <code>surveys</code> except <code>record_id</code>
and <code>species_id</code>.</p>
<p>To choose rows based on a specific criteria, use <code>filter()</code>:</p>
<div class="sourceCode" id="cb282"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb282-1"><a href="sec-dplyr.html#cb282-1" aria-hidden="true" tabindex="-1"></a><span class="fu">filter</span>(surveys, year <span class="sc">==</span> <span class="dv">1995</span>)</span></code></pre></div>
<pre><code>## # A tibble: 1,180 x 13
##    record_id month   day  year plot_id species_id sex   hindfoot_length weight
##        &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;   &lt;dbl&gt; &lt;chr&gt;      &lt;chr&gt;           &lt;dbl&gt;  &lt;dbl&gt;
##  1     22314     6     7  1995       2 NL         M                  34     NA
##  2     22728     9    23  1995       2 NL         F                  32    165
##  3     22899    10    28  1995       2 NL         F                  32    171
##  4     23032    12     2  1995       2 NL         F                  33     NA
##  5     22003     1    11  1995       2 DM         M                  37     41
##  6     22042     2     4  1995       2 DM         F                  36     45
##  7     22044     2     4  1995       2 DM         M                  37     46
##  8     22105     3     4  1995       2 DM         F                  37     49
##  9     22109     3     4  1995       2 DM         M                  37     46
## 10     22168     4     1  1995       2 DM         M                  36     48
## # … with 1,170 more rows, and 4 more variables: genus &lt;chr&gt;, species &lt;chr&gt;,
## #   taxa &lt;chr&gt;, plot_type &lt;chr&gt;</code></pre>
</div>
<div id="pipes" class="section level2" number="5.4">
<h2>
<span class="header-section-number">5.4</span> Pipes<div class="tooltip"><button class="internal-link-btn" onclick="copy_link('pipes')" onmouseout="reset_tooltip('pipes-tooltip')"><span class="tooltiptext" id="pipes-tooltip">Copy link</span><i class="fa fa-link"></i></button></div>
</h2>
<p>What if you want to select and filter at the same time? There are three
ways to do this: use intermediate steps, nested functions, or pipes.</p>
<p>With intermediate steps, you create a temporary data frame and use
that as input to the next function, like this:</p>
<div class="sourceCode" id="cb284"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb284-1"><a href="sec-dplyr.html#cb284-1" aria-hidden="true" tabindex="-1"></a>surveys2 <span class="ot">&lt;-</span> <span class="fu">filter</span>(surveys, weight <span class="sc">&lt;</span> <span class="dv">5</span>)</span>
<span id="cb284-2"><a href="sec-dplyr.html#cb284-2" aria-hidden="true" tabindex="-1"></a>surveys_sml <span class="ot">&lt;-</span> <span class="fu">select</span>(surveys2, species_id, sex, weight)</span></code></pre></div>
<p>This is readable, but can clutter up your workspace with lots of objects that you have to name individually. With multiple steps, that can be hard to keep track of.</p>
<p>You can also nest functions (i.e. one function inside of another), like this:</p>
<div class="sourceCode" id="cb285"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb285-1"><a href="sec-dplyr.html#cb285-1" aria-hidden="true" tabindex="-1"></a>surveys_sml <span class="ot">&lt;-</span> <span class="fu">select</span>(<span class="fu">filter</span>(surveys, weight <span class="sc">&lt;</span> <span class="dv">5</span>), species_id, sex, weight)</span></code></pre></div>
<p>This is handy, but can be difficult to read if too many functions are nested, as
R evaluates the expression from the inside out (in this case, filtering, then selecting).</p>
<p>The last option, <em>pipes</em>, are a recent addition to R. Pipes let you take
the output of one function and send it directly to the next, which is useful
when you need to do many things to the same dataset. Pipes in R look like
<code>%&gt;%</code> and are made available via the <strong><code>magrittr</code></strong> package, installed automatically
with <strong><code>dplyr</code></strong>. If you use RStudio, you can type the pipe with <kbd>Ctrl</kbd>
+ <kbd>Shift</kbd> + <kbd>M</kbd> if you have a PC or <kbd>Cmd</kbd> +
<kbd>Shift</kbd> + <kbd>M</kbd> if you have a Mac.</p>
<div class="sourceCode" id="cb286"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb286-1"><a href="sec-dplyr.html#cb286-1" aria-hidden="true" tabindex="-1"></a>surveys <span class="sc">%&gt;%</span></span>
<span id="cb286-2"><a href="sec-dplyr.html#cb286-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(weight <span class="sc">&lt;</span> <span class="dv">5</span>) <span class="sc">%&gt;%</span></span>
<span id="cb286-3"><a href="sec-dplyr.html#cb286-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(species_id, sex, weight)</span></code></pre></div>
<pre><code>## # A tibble: 17 x 3
##    species_id sex   weight
##    &lt;chr&gt;      &lt;chr&gt;  &lt;dbl&gt;
##  1 PF         F          4
##  2 PF         F          4
##  3 PF         M          4
##  4 RM         F          4
##  5 RM         M          4
##  6 PF         &lt;NA&gt;       4
##  7 PP         M          4
##  8 RM         M          4
##  9 RM         M          4
## 10 RM         M          4
## 11 PF         M          4
## 12 PF         F          4
## 13 RM         M          4
## 14 RM         M          4
## 15 RM         F          4
## 16 RM         M          4
## 17 RM         M          4</code></pre>
<p>In the above code, we use the pipe to send the <code>surveys</code> dataset first through
<code>filter()</code> to keep rows where <code>weight</code> is less than 5, then through <code>select()</code>
to keep only the <code>species_id</code>, <code>sex</code>, and <code>weight</code> columns. Since <code>%&gt;%</code> takes
the object on its left and passes it as the first argument to the function on
its right, we don’t need to explicitly include the data frame as an argument
to the <code>filter()</code> and <code>select()</code> functions any more.</p>
<p>Some may find it helpful to read the pipe like the word “then.” For instance,
in the above example, we took the data frame <code>surveys</code>, <em>then</em> we <code>filter</code>ed
for rows with <code>weight &lt; 5</code>, <em>then</em> we <code>select</code>ed columns <code>species_id</code>, <code>sex</code>,
and <code>weight</code>. The <strong><code>dplyr</code></strong> functions by themselves are somewhat simple,
but by combining them into linear workflows with the pipe, we can accomplish
more complex manipulations of data frames.</p>
<p>If we want to create a new object with this smaller version of the data, we
can assign it a new name:</p>
<div class="sourceCode" id="cb288"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb288-1"><a href="sec-dplyr.html#cb288-1" aria-hidden="true" tabindex="-1"></a>surveys_sml <span class="ot">&lt;-</span> surveys <span class="sc">%&gt;%</span></span>
<span id="cb288-2"><a href="sec-dplyr.html#cb288-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(weight <span class="sc">&lt;</span> <span class="dv">5</span>) <span class="sc">%&gt;%</span></span>
<span id="cb288-3"><a href="sec-dplyr.html#cb288-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(species_id, sex, weight)</span>
<span id="cb288-4"><a href="sec-dplyr.html#cb288-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb288-5"><a href="sec-dplyr.html#cb288-5" aria-hidden="true" tabindex="-1"></a>surveys_sml</span></code></pre></div>
<pre><code>## # A tibble: 17 x 3
##    species_id sex   weight
##    &lt;chr&gt;      &lt;chr&gt;  &lt;dbl&gt;
##  1 PF         F          4
##  2 PF         F          4
##  3 PF         M          4
##  4 RM         F          4
##  5 RM         M          4
##  6 PF         &lt;NA&gt;       4
##  7 PP         M          4
##  8 RM         M          4
##  9 RM         M          4
## 10 RM         M          4
## 11 PF         M          4
## 12 PF         F          4
## 13 RM         M          4
## 14 RM         M          4
## 15 RM         F          4
## 16 RM         M          4
## 17 RM         M          4</code></pre>
<p>Note that the final data frame is the leftmost part of this expression.</p>
<div class="question">
<p class="question-begin">
► Question
</p>
<div class="question-body">
<p>Using pipes, subset the <code>surveys</code> data to include animals collected
before 1995 and retain only the columns <code>year</code>, <code>sex</code>, and <code>weight</code>.</p>
<p class="question-end">
<span class="fa fa-square-o solution-icon"></span>
</p>
</div>
</div>
<div class="msmb-solution">
<p class="solution-begin">
► Solution<span id="sol-start-19" class="fa fa-plus-square solution-icon clickable" onclick="toggle_visibility('sol-body-19', 'sol-start-19')"></span>
</p>
<div id="sol-body-19" class="solution-body" style="display: none;">
<div class="sourceCode" id="cb290"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb290-1"><a href="sec-dplyr.html#cb290-1" aria-hidden="true" tabindex="-1"></a>surveys <span class="sc">%&gt;%</span></span>
<span id="cb290-2"><a href="sec-dplyr.html#cb290-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">filter</span>(year <span class="sc">&lt;</span> <span class="dv">1995</span>) <span class="sc">%&gt;%</span></span>
<span id="cb290-3"><a href="sec-dplyr.html#cb290-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">select</span>(year, sex, weight)</span></code></pre></div>
<pre><code>## # A tibble: 21,486 x 3
##     year sex   weight
##    &lt;dbl&gt; &lt;chr&gt;  &lt;dbl&gt;
##  1  1977 M         NA
##  2  1977 M         NA
##  3  1977 &lt;NA&gt;      NA
##  4  1977 &lt;NA&gt;      NA
##  5  1977 &lt;NA&gt;      NA
##  6  1977 &lt;NA&gt;      NA
##  7  1977 &lt;NA&gt;      NA
##  8  1978 &lt;NA&gt;      NA
##  9  1978 M        218
## 10  1978 &lt;NA&gt;      NA
## # … with 21,476 more rows</code></pre>
<p class="solution-end">
<span class="fa fa-square-o solution-icon"></span>
</p>
</div>
</div>
</div>
<div id="mutate" class="section level2" number="5.5">
<h2>
<span class="header-section-number">5.5</span> Mutate<div class="tooltip"><button class="internal-link-btn" onclick="copy_link('mutate')" onmouseout="reset_tooltip('mutate-tooltip')"><span class="tooltiptext" id="mutate-tooltip">Copy link</span><i class="fa fa-link"></i></button></div>
</h2>
<p>Frequently you’ll want to create new columns based on the values in existing
columns, for example to do unit conversions, or to find the ratio of values in two
columns. For this we’ll use <code>mutate()</code>.</p>
<p>To create a new column of weight in kg:</p>
<div class="sourceCode" id="cb292"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb292-1"><a href="sec-dplyr.html#cb292-1" aria-hidden="true" tabindex="-1"></a>surveys <span class="sc">%&gt;%</span></span>
<span id="cb292-2"><a href="sec-dplyr.html#cb292-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">weight_kg =</span> weight <span class="sc">/</span> <span class="dv">1000</span>)</span></code></pre></div>
<pre><code>## # A tibble: 34,786 x 14
##    record_id month   day  year plot_id species_id sex   hindfoot_length weight
##        &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;   &lt;dbl&gt; &lt;chr&gt;      &lt;chr&gt;           &lt;dbl&gt;  &lt;dbl&gt;
##  1         1     7    16  1977       2 NL         M                  32     NA
##  2        72     8    19  1977       2 NL         M                  31     NA
##  3       224     9    13  1977       2 NL         &lt;NA&gt;               NA     NA
##  4       266    10    16  1977       2 NL         &lt;NA&gt;               NA     NA
##  5       349    11    12  1977       2 NL         &lt;NA&gt;               NA     NA
##  6       363    11    12  1977       2 NL         &lt;NA&gt;               NA     NA
##  7       435    12    10  1977       2 NL         &lt;NA&gt;               NA     NA
##  8       506     1     8  1978       2 NL         &lt;NA&gt;               NA     NA
##  9       588     2    18  1978       2 NL         M                  NA    218
## 10       661     3    11  1978       2 NL         &lt;NA&gt;               NA     NA
## # … with 34,776 more rows, and 5 more variables: genus &lt;chr&gt;, species &lt;chr&gt;,
## #   taxa &lt;chr&gt;, plot_type &lt;chr&gt;, weight_kg &lt;dbl&gt;</code></pre>
<p>You can also create a second new column based on the first new column within the same call of <code>mutate()</code>:</p>
<div class="sourceCode" id="cb294"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb294-1"><a href="sec-dplyr.html#cb294-1" aria-hidden="true" tabindex="-1"></a>surveys <span class="sc">%&gt;%</span></span>
<span id="cb294-2"><a href="sec-dplyr.html#cb294-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">weight_kg =</span> weight <span class="sc">/</span> <span class="dv">1000</span>,</span>
<span id="cb294-3"><a href="sec-dplyr.html#cb294-3" aria-hidden="true" tabindex="-1"></a>         <span class="at">weight_kg2 =</span> weight_kg <span class="sc">*</span> <span class="dv">2</span>)</span></code></pre></div>
<pre><code>## # A tibble: 34,786 x 15
##    record_id month   day  year plot_id species_id sex   hindfoot_length weight
##        &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;   &lt;dbl&gt; &lt;chr&gt;      &lt;chr&gt;           &lt;dbl&gt;  &lt;dbl&gt;
##  1         1     7    16  1977       2 NL         M                  32     NA
##  2        72     8    19  1977       2 NL         M                  31     NA
##  3       224     9    13  1977       2 NL         &lt;NA&gt;               NA     NA
##  4       266    10    16  1977       2 NL         &lt;NA&gt;               NA     NA
##  5       349    11    12  1977       2 NL         &lt;NA&gt;               NA     NA
##  6       363    11    12  1977       2 NL         &lt;NA&gt;               NA     NA
##  7       435    12    10  1977       2 NL         &lt;NA&gt;               NA     NA
##  8       506     1     8  1978       2 NL         &lt;NA&gt;               NA     NA
##  9       588     2    18  1978       2 NL         M                  NA    218
## 10       661     3    11  1978       2 NL         &lt;NA&gt;               NA     NA
## # … with 34,776 more rows, and 6 more variables: genus &lt;chr&gt;, species &lt;chr&gt;,
## #   taxa &lt;chr&gt;, plot_type &lt;chr&gt;, weight_kg &lt;dbl&gt;, weight_kg2 &lt;dbl&gt;</code></pre>
<p>If this runs off your screen and you just want to see the first few rows, you
can use a pipe to view the <code>head()</code> of the data. (Pipes work with non-<strong><code>dplyr</code></strong>
functions, too, as long as the <strong><code>dplyr</code></strong> or <code>magrittr</code> package is loaded).</p>
<div class="sourceCode" id="cb296"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb296-1"><a href="sec-dplyr.html#cb296-1" aria-hidden="true" tabindex="-1"></a>surveys <span class="sc">%&gt;%</span></span>
<span id="cb296-2"><a href="sec-dplyr.html#cb296-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">weight_kg =</span> weight <span class="sc">/</span> <span class="dv">1000</span>) <span class="sc">%&gt;%</span></span>
<span id="cb296-3"><a href="sec-dplyr.html#cb296-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">head</span>()</span></code></pre></div>
<pre><code>## # A tibble: 6 x 14
##   record_id month   day  year plot_id species_id sex   hindfoot_length weight
##       &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;   &lt;dbl&gt; &lt;chr&gt;      &lt;chr&gt;           &lt;dbl&gt;  &lt;dbl&gt;
## 1         1     7    16  1977       2 NL         M                  32     NA
## 2        72     8    19  1977       2 NL         M                  31     NA
## 3       224     9    13  1977       2 NL         &lt;NA&gt;               NA     NA
## 4       266    10    16  1977       2 NL         &lt;NA&gt;               NA     NA
## 5       349    11    12  1977       2 NL         &lt;NA&gt;               NA     NA
## 6       363    11    12  1977       2 NL         &lt;NA&gt;               NA     NA
## # … with 5 more variables: genus &lt;chr&gt;, species &lt;chr&gt;, taxa &lt;chr&gt;,
## #   plot_type &lt;chr&gt;, weight_kg &lt;dbl&gt;</code></pre>
<p>The first few rows of the output are full of <code>NA</code>s, so if we wanted to remove
those we could insert a <code>filter()</code> in the chain:</p>
<div class="sourceCode" id="cb298"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb298-1"><a href="sec-dplyr.html#cb298-1" aria-hidden="true" tabindex="-1"></a>surveys <span class="sc">%&gt;%</span></span>
<span id="cb298-2"><a href="sec-dplyr.html#cb298-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="sc">!</span><span class="fu">is.na</span>(weight)) <span class="sc">%&gt;%</span></span>
<span id="cb298-3"><a href="sec-dplyr.html#cb298-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">weight_kg =</span> weight <span class="sc">/</span> <span class="dv">1000</span>) <span class="sc">%&gt;%</span></span>
<span id="cb298-4"><a href="sec-dplyr.html#cb298-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">head</span>()</span></code></pre></div>
<pre><code>## # A tibble: 6 x 14
##   record_id month   day  year plot_id species_id sex   hindfoot_length weight
##       &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;   &lt;dbl&gt; &lt;chr&gt;      &lt;chr&gt;           &lt;dbl&gt;  &lt;dbl&gt;
## 1       588     2    18  1978       2 NL         M                  NA    218
## 2       845     5     6  1978       2 NL         M                  32    204
## 3       990     6     9  1978       2 NL         M                  NA    200
## 4      1164     8     5  1978       2 NL         M                  34    199
## 5      1261     9     4  1978       2 NL         M                  32    197
## 6      1453    11     5  1978       2 NL         M                  NA    218
## # … with 5 more variables: genus &lt;chr&gt;, species &lt;chr&gt;, taxa &lt;chr&gt;,
## #   plot_type &lt;chr&gt;, weight_kg &lt;dbl&gt;</code></pre>
<p><code>is.na()</code> is a function that determines whether something is an <code>NA</code>. The <code>!</code>
symbol negates the result, so we’re asking for every row where weight <em>is not</em> an <code>NA</code>.</p>
<div class="question">
<p class="question-begin">
► Question
</p>
<div class="question-body">
<p>Create a new data frame from the <code>surveys</code> data that meets the
following criteria: contains only the <code>species_id</code> column and a new
column called <code>hindfoot_half</code> containing values that are half the
<code>hindfoot_length</code> values. In this <code>hindfoot_half</code> column, there are
no <code>NA</code>s and all values are less than 30.</p>
<p><strong>Hint</strong>: think about how the commands should be ordered to produce
this data frame!</p>
<p class="question-end">
<span class="fa fa-square-o solution-icon"></span>
</p>
</div>
</div>
<div class="msmb-solution">
<p class="solution-begin">
► Solution<span id="sol-start-20" class="fa fa-plus-square solution-icon clickable" onclick="toggle_visibility('sol-body-20', 'sol-start-20')"></span>
</p>
<div id="sol-body-20" class="solution-body" style="display: none;">
<div class="sourceCode" id="cb300"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb300-1"><a href="sec-dplyr.html#cb300-1" aria-hidden="true" tabindex="-1"></a>surveys_hindfoot_half <span class="ot">&lt;-</span> surveys <span class="sc">%&gt;%</span></span>
<span id="cb300-2"><a href="sec-dplyr.html#cb300-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">filter</span>(<span class="sc">!</span><span class="fu">is.na</span>(hindfoot_length)) <span class="sc">%&gt;%</span></span>
<span id="cb300-3"><a href="sec-dplyr.html#cb300-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">mutate</span>(<span class="at">hindfoot_half =</span> hindfoot_length <span class="sc">/</span> <span class="dv">2</span>) <span class="sc">%&gt;%</span></span>
<span id="cb300-4"><a href="sec-dplyr.html#cb300-4" aria-hidden="true" tabindex="-1"></a>    <span class="fu">filter</span>(hindfoot_half <span class="sc">&lt;</span> <span class="dv">30</span>) <span class="sc">%&gt;%</span></span>
<span id="cb300-5"><a href="sec-dplyr.html#cb300-5" aria-hidden="true" tabindex="-1"></a>    <span class="fu">select</span>(species_id, hindfoot_half)</span></code></pre></div>
<p class="solution-end">
<span class="fa fa-square-o solution-icon"></span>
</p>
</div>
</div>
</div>
<div id="split-apply-combine-data-analysis" class="section level2" number="5.6">
<h2>
<span class="header-section-number">5.6</span> Split-apply-combine data analysis<div class="tooltip"><button class="internal-link-btn" onclick="copy_link('split-apply-combine-data-analysis')" onmouseout="reset_tooltip('split-apply-combine-data-analysis-tooltip')"><span class="tooltiptext" id="split-apply-combine-data-analysis-tooltip">Copy link</span><i class="fa fa-link"></i></button></div>
</h2>
<p>Many data analysis tasks can be approached using the
<em>split-apply-combine</em> paradigm: split the data into groups, apply some
analysis to each group, and then combine the results. <strong><code>dplyr</code></strong>
makes this very easy through the use of the <code>group_by()</code> function.</p>
<div class="sourceCode" id="cb301"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb301-1"><a href="sec-dplyr.html#cb301-1" aria-hidden="true" tabindex="-1"></a>surveys <span class="sc">%&gt;%</span></span>
<span id="cb301-2"><a href="sec-dplyr.html#cb301-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(sex)</span></code></pre></div>
<pre><code>## # A tibble: 34,786 x 13
## # Groups:   sex [3]
##    record_id month   day  year plot_id species_id sex   hindfoot_length weight
##        &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;   &lt;dbl&gt; &lt;chr&gt;      &lt;chr&gt;           &lt;dbl&gt;  &lt;dbl&gt;
##  1         1     7    16  1977       2 NL         M                  32     NA
##  2        72     8    19  1977       2 NL         M                  31     NA
##  3       224     9    13  1977       2 NL         &lt;NA&gt;               NA     NA
##  4       266    10    16  1977       2 NL         &lt;NA&gt;               NA     NA
##  5       349    11    12  1977       2 NL         &lt;NA&gt;               NA     NA
##  6       363    11    12  1977       2 NL         &lt;NA&gt;               NA     NA
##  7       435    12    10  1977       2 NL         &lt;NA&gt;               NA     NA
##  8       506     1     8  1978       2 NL         &lt;NA&gt;               NA     NA
##  9       588     2    18  1978       2 NL         M                  NA    218
## 10       661     3    11  1978       2 NL         &lt;NA&gt;               NA     NA
## # … with 34,776 more rows, and 4 more variables: genus &lt;chr&gt;, species &lt;chr&gt;,
## #   taxa &lt;chr&gt;, plot_type &lt;chr&gt;</code></pre>
<p>The <code>group_by()</code> function doesn’t perform any data processing, it
groups the data into subsets: in the example above, our initial
<code>tibble</code> of 34786 observations is split into
3 groups based on the <code>sex</code> variable.</p>
<p>Once the data have been combined, subsequent operations will be
applied on each group independently.</p>
<div id="the-summarize-function" class="section level3" number="5.6.1">
<h3>
<span class="header-section-number">5.6.1</span> The <code>summarize()</code> function<div class="tooltip"><button class="internal-link-btn" onclick="copy_link('the-summarize-function')" onmouseout="reset_tooltip('the-summarize-function-tooltip')"><span class="tooltiptext" id="the-summarize-function-tooltip">Copy link</span><i class="fa fa-link"></i></button></div>
</h3>
<p><code>group_by()</code> is often used together with <code>summarize()</code>, which
collapses each group into a single-row summary of that group.
<code>group_by()</code> takes as arguments the column names that contain the
<strong>categorical</strong> variables for which you want to calculate the summary
statistics. So to compute the mean <code>weight</code> by sex:</p>
<div class="sourceCode" id="cb303"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb303-1"><a href="sec-dplyr.html#cb303-1" aria-hidden="true" tabindex="-1"></a>surveys <span class="sc">%&gt;%</span></span>
<span id="cb303-2"><a href="sec-dplyr.html#cb303-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(sex) <span class="sc">%&gt;%</span></span>
<span id="cb303-3"><a href="sec-dplyr.html#cb303-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">mean_weight =</span> <span class="fu">mean</span>(weight, <span class="at">na.rm =</span> <span class="cn">TRUE</span>))</span></code></pre></div>
<pre><code>## # A tibble: 3 x 2
##   sex   mean_weight
##   &lt;chr&gt;       &lt;dbl&gt;
## 1 F            42.2
## 2 M            43.0
## 3 &lt;NA&gt;         64.7</code></pre>
<p>You may also have noticed that the output from these calls doesn’t run off the
screen anymore. It’s one of the advantages of <code>tbl_df</code> over data frame.</p>
<p>You can also group by multiple columns:</p>
<div class="sourceCode" id="cb305"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb305-1"><a href="sec-dplyr.html#cb305-1" aria-hidden="true" tabindex="-1"></a>surveys <span class="sc">%&gt;%</span></span>
<span id="cb305-2"><a href="sec-dplyr.html#cb305-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(sex, species_id) <span class="sc">%&gt;%</span></span>
<span id="cb305-3"><a href="sec-dplyr.html#cb305-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">mean_weight =</span> <span class="fu">mean</span>(weight, <span class="at">na.rm =</span> <span class="cn">TRUE</span>))</span></code></pre></div>
<pre><code>## `summarise()` has grouped output by 'sex'. You can override using the `.groups` argument.</code></pre>
<pre><code>## # A tibble: 92 x 3
## # Groups:   sex [3]
##    sex   species_id mean_weight
##    &lt;chr&gt; &lt;chr&gt;            &lt;dbl&gt;
##  1 F     BA                9.16
##  2 F     DM               41.6 
##  3 F     DO               48.5 
##  4 F     DS              118.  
##  5 F     NL              154.  
##  6 F     OL               31.1 
##  7 F     OT               24.8 
##  8 F     OX               21   
##  9 F     PB               30.2 
## 10 F     PE               22.8 
## # … with 82 more rows</code></pre>
<p>When grouping both by <code>sex</code> and <code>species_id</code>, the last few rows are for animals
that escaped before their sex and body weights could be determined. You may notice
that the last column does not contain <code>NA</code> but <code>NaN</code> (which refers to “Not a
Number”). To avoid this, we can remove the missing values for weight before we
attempt to calculate the summary statistics on weight. Because the missing
values are removed first, we can omit <code>na.rm = TRUE</code> when computing the mean:</p>
<div class="sourceCode" id="cb308"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb308-1"><a href="sec-dplyr.html#cb308-1" aria-hidden="true" tabindex="-1"></a>surveys <span class="sc">%&gt;%</span></span>
<span id="cb308-2"><a href="sec-dplyr.html#cb308-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="sc">!</span><span class="fu">is.na</span>(weight)) <span class="sc">%&gt;%</span></span>
<span id="cb308-3"><a href="sec-dplyr.html#cb308-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(sex, species_id) <span class="sc">%&gt;%</span></span>
<span id="cb308-4"><a href="sec-dplyr.html#cb308-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">mean_weight =</span> <span class="fu">mean</span>(weight))</span></code></pre></div>
<pre><code>## `summarise()` has grouped output by 'sex'. You can override using the `.groups` argument.</code></pre>
<pre><code>## # A tibble: 64 x 3
## # Groups:   sex [3]
##    sex   species_id mean_weight
##    &lt;chr&gt; &lt;chr&gt;            &lt;dbl&gt;
##  1 F     BA                9.16
##  2 F     DM               41.6 
##  3 F     DO               48.5 
##  4 F     DS              118.  
##  5 F     NL              154.  
##  6 F     OL               31.1 
##  7 F     OT               24.8 
##  8 F     OX               21   
##  9 F     PB               30.2 
## 10 F     PE               22.8 
## # … with 54 more rows</code></pre>
<p>Here, again, the output from these calls doesn’t run off the screen
anymore. If you want to display more data, you can use the <code>print()</code> function
at the end of your chain with the argument <code>n</code> specifying the number of rows to
display:</p>
<div class="sourceCode" id="cb311"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb311-1"><a href="sec-dplyr.html#cb311-1" aria-hidden="true" tabindex="-1"></a>surveys <span class="sc">%&gt;%</span></span>
<span id="cb311-2"><a href="sec-dplyr.html#cb311-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="sc">!</span><span class="fu">is.na</span>(weight)) <span class="sc">%&gt;%</span></span>
<span id="cb311-3"><a href="sec-dplyr.html#cb311-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(sex, species_id) <span class="sc">%&gt;%</span></span>
<span id="cb311-4"><a href="sec-dplyr.html#cb311-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">mean_weight =</span> <span class="fu">mean</span>(weight)) <span class="sc">%&gt;%</span></span>
<span id="cb311-5"><a href="sec-dplyr.html#cb311-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">print</span>(<span class="at">n =</span> <span class="dv">15</span>)</span></code></pre></div>
<pre><code>## `summarise()` has grouped output by 'sex'. You can override using the `.groups` argument.</code></pre>
<pre><code>## # A tibble: 64 x 3
## # Groups:   sex [3]
##    sex   species_id mean_weight
##    &lt;chr&gt; &lt;chr&gt;            &lt;dbl&gt;
##  1 F     BA                9.16
##  2 F     DM               41.6 
##  3 F     DO               48.5 
##  4 F     DS              118.  
##  5 F     NL              154.  
##  6 F     OL               31.1 
##  7 F     OT               24.8 
##  8 F     OX               21   
##  9 F     PB               30.2 
## 10 F     PE               22.8 
## 11 F     PF                7.97
## 12 F     PH               30.8 
## 13 F     PL               19.3 
## 14 F     PM               22.1 
## 15 F     PP               17.2 
## # … with 49 more rows</code></pre>
<p>Once the data are grouped, you can also summarize multiple variables at the same
time (and not necessarily on the same variable). For instance, we could add a
column indicating the minimum weight for each species for each sex:</p>
<div class="sourceCode" id="cb314"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb314-1"><a href="sec-dplyr.html#cb314-1" aria-hidden="true" tabindex="-1"></a>surveys <span class="sc">%&gt;%</span></span>
<span id="cb314-2"><a href="sec-dplyr.html#cb314-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="sc">!</span><span class="fu">is.na</span>(weight)) <span class="sc">%&gt;%</span></span>
<span id="cb314-3"><a href="sec-dplyr.html#cb314-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(sex, species_id) <span class="sc">%&gt;%</span></span>
<span id="cb314-4"><a href="sec-dplyr.html#cb314-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">mean_weight =</span> <span class="fu">mean</span>(weight),</span>
<span id="cb314-5"><a href="sec-dplyr.html#cb314-5" aria-hidden="true" tabindex="-1"></a>            <span class="at">min_weight =</span> <span class="fu">min</span>(weight))</span></code></pre></div>
<pre><code>## `summarise()` has grouped output by 'sex'. You can override using the `.groups` argument.</code></pre>
<pre><code>## # A tibble: 64 x 4
## # Groups:   sex [3]
##    sex   species_id mean_weight min_weight
##    &lt;chr&gt; &lt;chr&gt;            &lt;dbl&gt;      &lt;dbl&gt;
##  1 F     BA                9.16          6
##  2 F     DM               41.6          10
##  3 F     DO               48.5          12
##  4 F     DS              118.           45
##  5 F     NL              154.           32
##  6 F     OL               31.1          10
##  7 F     OT               24.8           5
##  8 F     OX               21            20
##  9 F     PB               30.2          12
## 10 F     PE               22.8          11
## # … with 54 more rows</code></pre>
<p>It is sometimes useful to rearrange the result of a query to inspect the values. For instance, we can sort on <code>min_weight</code> to put the lighter species first:</p>
<div class="sourceCode" id="cb317"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb317-1"><a href="sec-dplyr.html#cb317-1" aria-hidden="true" tabindex="-1"></a>surveys <span class="sc">%&gt;%</span></span>
<span id="cb317-2"><a href="sec-dplyr.html#cb317-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="sc">!</span><span class="fu">is.na</span>(weight)) <span class="sc">%&gt;%</span></span>
<span id="cb317-3"><a href="sec-dplyr.html#cb317-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(sex, species_id) <span class="sc">%&gt;%</span></span>
<span id="cb317-4"><a href="sec-dplyr.html#cb317-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">mean_weight =</span> <span class="fu">mean</span>(weight),</span>
<span id="cb317-5"><a href="sec-dplyr.html#cb317-5" aria-hidden="true" tabindex="-1"></a>            <span class="at">min_weight =</span> <span class="fu">min</span>(weight)) <span class="sc">%&gt;%</span></span>
<span id="cb317-6"><a href="sec-dplyr.html#cb317-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(min_weight)</span></code></pre></div>
<pre><code>## `summarise()` has grouped output by 'sex'. You can override using the `.groups` argument.</code></pre>
<pre><code>## # A tibble: 64 x 4
## # Groups:   sex [3]
##    sex   species_id mean_weight min_weight
##    &lt;chr&gt; &lt;chr&gt;            &lt;dbl&gt;      &lt;dbl&gt;
##  1 F     PF                7.97          4
##  2 F     RM               11.1           4
##  3 M     PF                7.89          4
##  4 M     PP               17.2           4
##  5 M     RM               10.1           4
##  6 &lt;NA&gt;  PF                6             4
##  7 F     OT               24.8           5
##  8 F     PP               17.2           5
##  9 F     BA                9.16          6
## 10 M     BA                7.36          6
## # … with 54 more rows</code></pre>
<p>To sort in descending order, we need to add the <code>desc()</code> function. If we want to sort the results by decreasing order of mean weight:</p>
<div class="sourceCode" id="cb320"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb320-1"><a href="sec-dplyr.html#cb320-1" aria-hidden="true" tabindex="-1"></a>surveys <span class="sc">%&gt;%</span></span>
<span id="cb320-2"><a href="sec-dplyr.html#cb320-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="sc">!</span><span class="fu">is.na</span>(weight)) <span class="sc">%&gt;%</span></span>
<span id="cb320-3"><a href="sec-dplyr.html#cb320-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(sex, species_id) <span class="sc">%&gt;%</span></span>
<span id="cb320-4"><a href="sec-dplyr.html#cb320-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">mean_weight =</span> <span class="fu">mean</span>(weight),</span>
<span id="cb320-5"><a href="sec-dplyr.html#cb320-5" aria-hidden="true" tabindex="-1"></a>            <span class="at">min_weight =</span> <span class="fu">min</span>(weight)) <span class="sc">%&gt;%</span></span>
<span id="cb320-6"><a href="sec-dplyr.html#cb320-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(<span class="fu">desc</span>(mean_weight))</span></code></pre></div>
<pre><code>## `summarise()` has grouped output by 'sex'. You can override using the `.groups` argument.</code></pre>
<pre><code>## # A tibble: 64 x 4
## # Groups:   sex [3]
##    sex   species_id mean_weight min_weight
##    &lt;chr&gt; &lt;chr&gt;            &lt;dbl&gt;      &lt;dbl&gt;
##  1 &lt;NA&gt;  NL               168.          83
##  2 M     NL               166.          30
##  3 F     NL               154.          32
##  4 M     SS               130          130
##  5 &lt;NA&gt;  SH               130          130
##  6 M     DS               122.          12
##  7 &lt;NA&gt;  DS               120           78
##  8 F     DS               118.          45
##  9 F     SH                78.8         30
## 10 F     SF                69           46
## # … with 54 more rows</code></pre>
</div>
<div id="counting" class="section level3" number="5.6.2">
<h3>
<span class="header-section-number">5.6.2</span> Counting<div class="tooltip"><button class="internal-link-btn" onclick="copy_link('counting')" onmouseout="reset_tooltip('counting-tooltip')"><span class="tooltiptext" id="counting-tooltip">Copy link</span><i class="fa fa-link"></i></button></div>
</h3>
<p>When working with data, we often want to know the number of observations found
for each factor or combination of factors. For this task, <strong><code>dplyr</code></strong> provides
<code>count()</code>. For example, if we wanted to count the number of rows of data for
each sex, we would do:</p>
<div class="sourceCode" id="cb323"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb323-1"><a href="sec-dplyr.html#cb323-1" aria-hidden="true" tabindex="-1"></a>surveys <span class="sc">%&gt;%</span></span>
<span id="cb323-2"><a href="sec-dplyr.html#cb323-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">count</span>(sex)</span></code></pre></div>
<pre><code>## # A tibble: 3 x 2
##   sex       n
##   &lt;chr&gt; &lt;int&gt;
## 1 F     15690
## 2 M     17348
## 3 &lt;NA&gt;   1748</code></pre>
<p>The <code>count()</code> function is shorthand for something we’ve already seen: grouping by a variable, and summarizing it by counting the number of observations in that group. In other words, <code>surveys %&gt;% count()</code> is equivalent to:</p>
<div class="sourceCode" id="cb325"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb325-1"><a href="sec-dplyr.html#cb325-1" aria-hidden="true" tabindex="-1"></a>surveys <span class="sc">%&gt;%</span></span>
<span id="cb325-2"><a href="sec-dplyr.html#cb325-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">group_by</span>(sex) <span class="sc">%&gt;%</span></span>
<span id="cb325-3"><a href="sec-dplyr.html#cb325-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">summarise</span>(<span class="at">count =</span> <span class="fu">n</span>())</span></code></pre></div>
<pre><code>## # A tibble: 3 x 2
##   sex   count
##   &lt;chr&gt; &lt;int&gt;
## 1 F     15690
## 2 M     17348
## 3 &lt;NA&gt;   1748</code></pre>
<p>For convenience, <code>count()</code> provides the <code>sort</code> argument:</p>
<div class="sourceCode" id="cb327"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb327-1"><a href="sec-dplyr.html#cb327-1" aria-hidden="true" tabindex="-1"></a>surveys <span class="sc">%&gt;%</span></span>
<span id="cb327-2"><a href="sec-dplyr.html#cb327-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">count</span>(sex, <span class="at">sort =</span> <span class="cn">TRUE</span>)</span></code></pre></div>
<pre><code>## # A tibble: 3 x 2
##   sex       n
##   &lt;chr&gt; &lt;int&gt;
## 1 M     17348
## 2 F     15690
## 3 &lt;NA&gt;   1748</code></pre>
<p>Previous example shows the use of <code>count()</code> to count the number of rows/observations
for <em>one</em> factor (i.e., <code>sex</code>).
If we wanted to count <em>combination of factors</em>, such as <code>sex</code> and <code>species</code>,
we would specify the first and the second factor as the arguments of <code>count()</code>:</p>
<div class="sourceCode" id="cb329"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb329-1"><a href="sec-dplyr.html#cb329-1" aria-hidden="true" tabindex="-1"></a>surveys <span class="sc">%&gt;%</span></span>
<span id="cb329-2"><a href="sec-dplyr.html#cb329-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">count</span>(sex, species)</span></code></pre></div>
<pre><code>## # A tibble: 81 x 3
##    sex   species         n
##    &lt;chr&gt; &lt;chr&gt;       &lt;int&gt;
##  1 F     albigula      675
##  2 F     baileyi      1646
##  3 F     eremicus      579
##  4 F     flavus        757
##  5 F     fulvescens     57
##  6 F     fulviventer    17
##  7 F     hispidus       99
##  8 F     leucogaster   475
##  9 F     leucopus       16
## 10 F     maniculatus   382
## # … with 71 more rows</code></pre>
<p>With the above code, we can proceed with <code>arrange()</code> to sort the table
according to a number of criteria so that we have a better comparison.
For instance, we might want to arrange the table above in (i) an alphabetical order of
the levels of the species and (ii) in descending order of the count:</p>
<div class="sourceCode" id="cb331"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb331-1"><a href="sec-dplyr.html#cb331-1" aria-hidden="true" tabindex="-1"></a>surveys <span class="sc">%&gt;%</span></span>
<span id="cb331-2"><a href="sec-dplyr.html#cb331-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">count</span>(sex, species) <span class="sc">%&gt;%</span></span>
<span id="cb331-3"><a href="sec-dplyr.html#cb331-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(species, <span class="fu">desc</span>(n))</span></code></pre></div>
<pre><code>## # A tibble: 81 x 3
##    sex   species             n
##    &lt;chr&gt; &lt;chr&gt;           &lt;int&gt;
##  1 F     albigula          675
##  2 M     albigula          502
##  3 &lt;NA&gt;  albigula           75
##  4 &lt;NA&gt;  audubonii          75
##  5 F     baileyi          1646
##  6 M     baileyi          1216
##  7 &lt;NA&gt;  baileyi            29
##  8 &lt;NA&gt;  bilineata         303
##  9 &lt;NA&gt;  brunneicapillus    50
## 10 &lt;NA&gt;  chlorurus          39
## # … with 71 more rows</code></pre>
<p>From the table above, we may learn that, for instance, there are 75 observations of
the <em>albigula</em> species that are not specified for its sex (i.e. <code>NA</code>).</p>
<div class="question">
<p class="question-begin">
► Question
</p>
<div class="question-body">
<ol style="list-style-type: decimal">
<li><p>How many animals were caught in each <code>plot_type</code> surveyed?</p></li>
<li><p>Use <code>group_by()</code> and <code>summarize()</code> to find the mean, min, and max
hindfoot length for each species (using <code>species_id</code>). Also add the
number of observations (hint: see <code>?n</code>).</p></li>
<li><p>What was the heaviest animal measured in each year? Return the columns <code>year</code>,
<code>genus</code>, <code>species_id</code>, and <code>weight</code>.</p></li>
</ol>
<p class="question-end">
<span class="fa fa-square-o solution-icon"></span>
</p>
</div>
</div>
<div class="msmb-solution">
<p class="solution-begin">
► Solution<span id="sol-start-21" class="fa fa-plus-square solution-icon clickable" onclick="toggle_visibility('sol-body-21', 'sol-start-21')"></span>
</p>
<div id="sol-body-21" class="solution-body" style="display: none;">
<ol style="list-style-type: decimal">
<li>How many animals were caught in each <code>plot_type</code> surveyed?</li>
</ol>
<div class="sourceCode" id="cb333"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb333-1"><a href="sec-dplyr.html#cb333-1" aria-hidden="true" tabindex="-1"></a>surveys <span class="sc">%&gt;%</span></span>
<span id="cb333-2"><a href="sec-dplyr.html#cb333-2" aria-hidden="true" tabindex="-1"></a>     <span class="fu">count</span>(plot_type)</span></code></pre></div>
<pre><code>## # A tibble: 5 x 2
##   plot_type                     n
##   &lt;chr&gt;                     &lt;int&gt;
## 1 Control                   15611
## 2 Long-term Krat Exclosure   5118
## 3 Rodent Exclosure           4233
## 4 Short-term Krat Exclosure  5906
## 5 Spectab exclosure          3918</code></pre>
<ol start="2" style="list-style-type: decimal">
<li>Use <code>group_by()</code> and <code>summarize()</code> to find the mean, min, and max
hindfoot length for each species (using <code>species_id</code>). Also add the
number of observations (hint: see <code>?n</code>).</li>
</ol>
<div class="sourceCode" id="cb335"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb335-1"><a href="sec-dplyr.html#cb335-1" aria-hidden="true" tabindex="-1"></a>surveys <span class="sc">%&gt;%</span></span>
<span id="cb335-2"><a href="sec-dplyr.html#cb335-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">filter</span>(<span class="sc">!</span><span class="fu">is.na</span>(hindfoot_length)) <span class="sc">%&gt;%</span></span>
<span id="cb335-3"><a href="sec-dplyr.html#cb335-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">group_by</span>(species_id) <span class="sc">%&gt;%</span></span>
<span id="cb335-4"><a href="sec-dplyr.html#cb335-4" aria-hidden="true" tabindex="-1"></a>    <span class="fu">summarize</span>(</span>
<span id="cb335-5"><a href="sec-dplyr.html#cb335-5" aria-hidden="true" tabindex="-1"></a>        <span class="at">mean_hindfoot_length =</span> <span class="fu">mean</span>(hindfoot_length),</span>
<span id="cb335-6"><a href="sec-dplyr.html#cb335-6" aria-hidden="true" tabindex="-1"></a>        <span class="at">min_hindfoot_length =</span> <span class="fu">min</span>(hindfoot_length),</span>
<span id="cb335-7"><a href="sec-dplyr.html#cb335-7" aria-hidden="true" tabindex="-1"></a>        <span class="at">max_hindfoot_length =</span> <span class="fu">max</span>(hindfoot_length),</span>
<span id="cb335-8"><a href="sec-dplyr.html#cb335-8" aria-hidden="true" tabindex="-1"></a>        <span class="at">n =</span> <span class="fu">n</span>()</span>
<span id="cb335-9"><a href="sec-dplyr.html#cb335-9" aria-hidden="true" tabindex="-1"></a>    )</span></code></pre></div>
<pre><code>## # A tibble: 25 x 5
##    species_id mean_hindfoot_length min_hindfoot_length max_hindfoot_length     n
##    &lt;chr&gt;                     &lt;dbl&gt;               &lt;dbl&gt;               &lt;dbl&gt; &lt;int&gt;
##  1 AH                         33                    31                  35     2
##  2 BA                         13                     6                  16    45
##  3 DM                         36.0                  16                  50  9972
##  4 DO                         35.6                  26                  64  2887
##  5 DS                         49.9                  39                  58  2132
##  6 NL                         32.3                  21                  70  1074
##  7 OL                         20.5                  12                  39   920
##  8 OT                         20.3                  13                  50  2139
##  9 OX                         19.1                  13                  21     8
## 10 PB                         26.1                   2                  47  2864
## # … with 15 more rows</code></pre>
<ol start="3" style="list-style-type: decimal">
<li>What was the heaviest animal measured in each year? Return the columns <code>year</code>,
<code>genus</code>, <code>species_id</code>, and <code>weight</code>.</li>
</ol>
<div class="sourceCode" id="cb337"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb337-1"><a href="sec-dplyr.html#cb337-1" aria-hidden="true" tabindex="-1"></a>surveys <span class="sc">%&gt;%</span></span>
<span id="cb337-2"><a href="sec-dplyr.html#cb337-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">filter</span>(<span class="sc">!</span><span class="fu">is.na</span>(weight)) <span class="sc">%&gt;%</span></span>
<span id="cb337-3"><a href="sec-dplyr.html#cb337-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">group_by</span>(year) <span class="sc">%&gt;%</span></span>
<span id="cb337-4"><a href="sec-dplyr.html#cb337-4" aria-hidden="true" tabindex="-1"></a>    <span class="fu">filter</span>(weight <span class="sc">==</span> <span class="fu">max</span>(weight)) <span class="sc">%&gt;%</span></span>
<span id="cb337-5"><a href="sec-dplyr.html#cb337-5" aria-hidden="true" tabindex="-1"></a>    <span class="fu">select</span>(year, genus, species, weight) <span class="sc">%&gt;%</span></span>
<span id="cb337-6"><a href="sec-dplyr.html#cb337-6" aria-hidden="true" tabindex="-1"></a>    <span class="fu">arrange</span>(year)</span></code></pre></div>
<pre><code>## # A tibble: 27 x 4
## # Groups:   year [26]
##     year genus     species     weight
##    &lt;dbl&gt; &lt;chr&gt;     &lt;chr&gt;        &lt;dbl&gt;
##  1  1977 Dipodomys spectabilis    149
##  2  1978 Neotoma   albigula       232
##  3  1978 Neotoma   albigula       232
##  4  1979 Neotoma   albigula       274
##  5  1980 Neotoma   albigula       243
##  6  1981 Neotoma   albigula       264
##  7  1982 Neotoma   albigula       252
##  8  1983 Neotoma   albigula       256
##  9  1984 Neotoma   albigula       259
## 10  1985 Neotoma   albigula       225
## # … with 17 more rows</code></pre>
<p class="solution-end">
<span class="fa fa-square-o solution-icon"></span>
</p>
</div>
</div>
</div>
</div>
<div id="reshaping-data" class="section level2" number="5.7">
<h2>
<span class="header-section-number">5.7</span> Reshaping data<div class="tooltip"><button class="internal-link-btn" onclick="copy_link('reshaping-data')" onmouseout="reset_tooltip('reshaping-data-tooltip')"><span class="tooltiptext" id="reshaping-data-tooltip">Copy link</span><i class="fa fa-link"></i></button></div>
</h2>
<p>In the spreadsheet lesson (chapter <a href="sec-dataorg.html#sec:dataorg">1</a>), we discussed how
to structure our data leading to the four rules defining a tidy
dataset:</p>
<ol style="list-style-type: decimal">
<li>Each variable has its own column</li>
<li>Each observation has its own row</li>
<li>Each value must have its own cell</li>
<li>Each type of observational unit forms a table</li>
</ol>
<p>Here we examine the fourth rule:</p>
<blockquote>
<p>Each type of observational unit forms a table.</p>
</blockquote>
<p>In <code>surveys</code> , the rows of <code>surveys</code> contain the values of variables
associated with each record (the unit), values such the weight or sex
of each animal associated with each record. What if instead of
comparing records, we wanted to compare the different mean weight of
each species between plots? (Ignoring <code>plot_type</code> for simplicity).</p>
<p>We’d need to create a new table where each row (the unit) is comprise
of values of variables associated with each plot. In practical terms
this means the values of the species in <code>genus</code> would become the names
of column variables and the cells would contain the values of the mean
weight observed on each plot.</p>
<p>Having created a new table, it is therefore straightforward to explore
the relationship between the weight of different species within, and
between, the plots. The key point here is that we are still following
a tidy data structure, but we have <strong>reshaped</strong> the data according to
the observations of interest: average species weight per plot instead
of recordings per date.</p>
<p>The opposite transformation would be to transform column names into
values of a variable.</p>
<p>We can do both these of transformations with two <code>tidyr</code> functions,
<code>pivot_longer()</code> and <code>pivot_wider()</code> (see
<a href="https://tidyr.tidyverse.org/dev/articles/pivot.html">here</a> for
details).</p>
<div id="pivoting-the-data-into-a-wider-format" class="section level3" number="5.7.1">
<h3>
<span class="header-section-number">5.7.1</span> Pivoting the data into a wider format<div class="tooltip"><button class="internal-link-btn" onclick="copy_link('pivoting-the-data-into-a-wider-format')" onmouseout="reset_tooltip('pivoting-the-data-into-a-wider-format-tooltip')"><span class="tooltiptext" id="pivoting-the-data-into-a-wider-format-tooltip">Copy link</span><i class="fa fa-link"></i></button></div>
</h3>
<p><code>pivot_wider</code> takes three main arguments:</p>
<ol style="list-style-type: decimal">
<li>the data to be transformed;</li>
<li>the <code>names_from</code> column name whose values will become new column
names;</li>
<li>the <code>values_from</code> column name whose values will fill the new
columns.</li>
</ol>
<p>Note also the <code>values_fill</code> argument which, if set, fills in missing
values with the value provided.</p>
<p>Let’s use <code>pivot_wider()</code> to transform surveys to find the mean weight
of each species in each plot over the entire survey period. We use
<code>filter()</code>, <code>group_by()</code> and <code>summarise()</code> to filter our observations
and variables of interest, and create a new variable for the
<code>mean_weight</code>.</p>
<div class="sourceCode" id="cb339"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb339-1"><a href="sec-dplyr.html#cb339-1" aria-hidden="true" tabindex="-1"></a>surveys_gw <span class="ot">&lt;-</span> surveys <span class="sc">%&gt;%</span></span>
<span id="cb339-2"><a href="sec-dplyr.html#cb339-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="sc">!</span><span class="fu">is.na</span>(weight)) <span class="sc">%&gt;%</span></span>
<span id="cb339-3"><a href="sec-dplyr.html#cb339-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(genus, plot_id) <span class="sc">%&gt;%</span></span>
<span id="cb339-4"><a href="sec-dplyr.html#cb339-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">mean_weight =</span> <span class="fu">mean</span>(weight))</span></code></pre></div>
<pre><code>## `summarise()` has grouped output by 'genus'. You can override using the `.groups` argument.</code></pre>
<div class="sourceCode" id="cb341"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb341-1"><a href="sec-dplyr.html#cb341-1" aria-hidden="true" tabindex="-1"></a>surveys_gw</span></code></pre></div>
<pre><code>## # A tibble: 196 x 3
## # Groups:   genus [10]
##    genus       plot_id mean_weight
##    &lt;chr&gt;         &lt;dbl&gt;       &lt;dbl&gt;
##  1 Baiomys           1        7   
##  2 Baiomys           2        6   
##  3 Baiomys           3        8.61
##  4 Baiomys           5        7.75
##  5 Baiomys          18        9.5 
##  6 Baiomys          19        9.53
##  7 Baiomys          20        6   
##  8 Baiomys          21        6.67
##  9 Chaetodipus       1       22.2 
## 10 Chaetodipus       2       25.1 
## # … with 186 more rows</code></pre>
<p>This yields <code>surveys_gw</code> where the observations for each plot are
spread across multiple rows, 196 observations of 3 variables. Using
<code>pivot_wider()</code>, using new columns from the <code>genus</code> variable and new
values from <code>mean_weight</code>, this becomes 24 observations of 11
variables, one row for each plot. We again use pipes:</p>
<div class="sourceCode" id="cb343"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb343-1"><a href="sec-dplyr.html#cb343-1" aria-hidden="true" tabindex="-1"></a>surveys_wide <span class="ot">&lt;-</span> surveys_gw <span class="sc">%&gt;%</span></span>
<span id="cb343-2"><a href="sec-dplyr.html#cb343-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">pivot_wider</span>(<span class="at">names_from =</span> genus,</span>
<span id="cb343-3"><a href="sec-dplyr.html#cb343-3" aria-hidden="true" tabindex="-1"></a>                <span class="at">values_from =</span> mean_weight)</span>
<span id="cb343-4"><a href="sec-dplyr.html#cb343-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb343-5"><a href="sec-dplyr.html#cb343-5" aria-hidden="true" tabindex="-1"></a>surveys_wide</span></code></pre></div>
<pre><code>## # A tibble: 24 x 11
##    plot_id Baiomys Chaetodipus Dipodomys Neotoma Onychomys Perognathus
##      &lt;dbl&gt;   &lt;dbl&gt;       &lt;dbl&gt;     &lt;dbl&gt;   &lt;dbl&gt;     &lt;dbl&gt;       &lt;dbl&gt;
##  1       1    7           22.2      60.2    156.      27.7        9.62
##  2       2    6           25.1      55.7    169.      26.9        6.95
##  3       3    8.61        24.6      52.0    158.      26.0        7.51
##  4       5    7.75        18.0      51.1    190.      27.0        8.66
##  5      18    9.5         26.8      61.4    149.      26.6        8.62
##  6      19    9.53        26.4      43.3    120       23.8        8.09
##  7      20    6           25.1      65.9    155.      25.2        8.14
##  8      21    6.67        28.2      42.7    138.      24.6        9.19
##  9       4   NA           23.0      57.5    164.      28.1        7.82
## 10       6   NA           24.9      58.6    180.      25.9        7.81
## # … with 14 more rows, and 4 more variables: Peromyscus &lt;dbl&gt;,
## #   Reithrodontomys &lt;dbl&gt;, Sigmodon &lt;dbl&gt;, Spermophilus &lt;dbl&gt;</code></pre>
<p><img src="figs/spread_data_R.png"></p>
<p>We can now easily plot the comparisons between the weight of species
in different plots, although we may wish to fill in the missing values
first by setting <code>values_fill</code>.</p>
<div class="sourceCode" id="cb345"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb345-1"><a href="sec-dplyr.html#cb345-1" aria-hidden="true" tabindex="-1"></a>surveys_gw <span class="sc">%&gt;%</span></span>
<span id="cb345-2"><a href="sec-dplyr.html#cb345-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">pivot_wider</span>(<span class="at">names_from =</span> genus,</span>
<span id="cb345-3"><a href="sec-dplyr.html#cb345-3" aria-hidden="true" tabindex="-1"></a>                <span class="at">values_from =</span> mean_weight,</span>
<span id="cb345-4"><a href="sec-dplyr.html#cb345-4" aria-hidden="true" tabindex="-1"></a>                <span class="at">values_fill =</span> <span class="dv">0</span>)</span></code></pre></div>
<pre><code>## # A tibble: 24 x 11
##    plot_id Baiomys Chaetodipus Dipodomys Neotoma Onychomys Perognathus
##      &lt;dbl&gt;   &lt;dbl&gt;       &lt;dbl&gt;     &lt;dbl&gt;   &lt;dbl&gt;     &lt;dbl&gt;       &lt;dbl&gt;
##  1       1    7           22.2      60.2    156.      27.7        9.62
##  2       2    6           25.1      55.7    169.      26.9        6.95
##  3       3    8.61        24.6      52.0    158.      26.0        7.51
##  4       5    7.75        18.0      51.1    190.      27.0        8.66
##  5      18    9.5         26.8      61.4    149.      26.6        8.62
##  6      19    9.53        26.4      43.3    120       23.8        8.09
##  7      20    6           25.1      65.9    155.      25.2        8.14
##  8      21    6.67        28.2      42.7    138.      24.6        9.19
##  9       4    0           23.0      57.5    164.      28.1        7.82
## 10       6    0           24.9      58.6    180.      25.9        7.81
## # … with 14 more rows, and 4 more variables: Peromyscus &lt;dbl&gt;,
## #   Reithrodontomys &lt;dbl&gt;, Sigmodon &lt;dbl&gt;, Spermophilus &lt;dbl&gt;</code></pre>
</div>
<div id="pivoting-data-into-a-longer-format" class="section level3" number="5.7.2">
<h3>
<span class="header-section-number">5.7.2</span> Pivoting data into a longer format<div class="tooltip"><button class="internal-link-btn" onclick="copy_link('pivoting-data-into-a-longer-format')" onmouseout="reset_tooltip('pivoting-data-into-a-longer-format-tooltip')"><span class="tooltiptext" id="pivoting-data-into-a-longer-format-tooltip">Copy link</span><i class="fa fa-link"></i></button></div>
</h3>
<p>The opposing situation could occur if we had been provided with data
in the form of <code>surveys_wide</code>, where the genus names are column
names, but we wish to treat them as values of a genus variable
instead.</p>
<p>In this situation we are using the column names and turning them into
a pair of new variables. One variable represents the column names as
values, and the other variable contains the values previously
associated with the column names.</p>
<p><code>pivot_longer()</code> takes four main arguments:</p>
<ol style="list-style-type: decimal">
<li>the data to be transformed;</li>
<li>the new <code>names_to</code> column we wish to create and populate with the
current column names;</li>
<li>the new <code>values_to</code> column we wish to create and populate with
current values;</li>
<li>the names of the columns to be used to populate the <code>names_to</code> and
<code>values_to</code> variables (or to drop).</li>
</ol>
<p>To recreate <code>surveys_gw</code> from <code>surveys_wide</code> we would create a key
called <code>genus</code> and value called <code>mean_weight</code> and use all columns
except <code>plot_id</code> for the key variable. Here we drop <code>plot_id</code> column
with a minus sign.</p>
<div class="sourceCode" id="cb347"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb347-1"><a href="sec-dplyr.html#cb347-1" aria-hidden="true" tabindex="-1"></a>surveys_long <span class="ot">&lt;-</span> surveys_wide <span class="sc">%&gt;%</span></span>
<span id="cb347-2"><a href="sec-dplyr.html#cb347-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">pivot_longer</span>(<span class="at">names_to =</span> <span class="st">"genus"</span>,</span>
<span id="cb347-3"><a href="sec-dplyr.html#cb347-3" aria-hidden="true" tabindex="-1"></a>                 <span class="at">values_to =</span> <span class="st">"mean_weight"</span>,</span>
<span id="cb347-4"><a href="sec-dplyr.html#cb347-4" aria-hidden="true" tabindex="-1"></a>                 <span class="sc">-</span>plot_id)</span>
<span id="cb347-5"><a href="sec-dplyr.html#cb347-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb347-6"><a href="sec-dplyr.html#cb347-6" aria-hidden="true" tabindex="-1"></a>surveys_long</span></code></pre></div>
<pre><code>## # A tibble: 240 x 3
##    plot_id genus           mean_weight
##      &lt;dbl&gt; &lt;chr&gt;                 &lt;dbl&gt;
##  1       1 Baiomys                7   
##  2       1 Chaetodipus           22.2 
##  3       1 Dipodomys             60.2 
##  4       1 Neotoma              156.  
##  5       1 Onychomys             27.7 
##  6       1 Perognathus            9.62
##  7       1 Peromyscus            22.2 
##  8       1 Reithrodontomys       11.4 
##  9       1 Sigmodon              NA   
## 10       1 Spermophilus          NA   
## # … with 230 more rows</code></pre>
<p><img src="figs/gather_data_R.png"></p>
<p>Note how the new variable names are to be quoted here. To get the same
output as we started with, we can arrange the data by <code>plot_id</code>:</p>
<div class="sourceCode" id="cb349"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb349-1"><a href="sec-dplyr.html#cb349-1" aria-hidden="true" tabindex="-1"></a>surveys_wide <span class="sc">%&gt;%</span></span>
<span id="cb349-2"><a href="sec-dplyr.html#cb349-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">pivot_longer</span>(<span class="at">names_to =</span> <span class="st">"genus"</span>,</span>
<span id="cb349-3"><a href="sec-dplyr.html#cb349-3" aria-hidden="true" tabindex="-1"></a>                 <span class="at">values_to =</span> <span class="st">"mean_weight"</span>,</span>
<span id="cb349-4"><a href="sec-dplyr.html#cb349-4" aria-hidden="true" tabindex="-1"></a>                 <span class="sc">-</span>plot_id) <span class="sc">%&gt;%</span></span>
<span id="cb349-5"><a href="sec-dplyr.html#cb349-5" aria-hidden="true" tabindex="-1"></a>    <span class="fu">arrange</span>(plot_id)</span></code></pre></div>
<pre><code>## # A tibble: 240 x 3
##    plot_id genus           mean_weight
##      &lt;dbl&gt; &lt;chr&gt;                 &lt;dbl&gt;
##  1       1 Baiomys                7   
##  2       1 Chaetodipus           22.2 
##  3       1 Dipodomys             60.2 
##  4       1 Neotoma              156.  
##  5       1 Onychomys             27.7 
##  6       1 Perognathus            9.62
##  7       1 Peromyscus            22.2 
##  8       1 Reithrodontomys       11.4 
##  9       1 Sigmodon              NA   
## 10       1 Spermophilus          NA   
## # … with 230 more rows</code></pre>
<p>Note that now the <code>NA</code> genera are included in the new wide
format. Pivoting to wider and longer formats can be a useful way to
balance out a dataset so every replicate has the same composition.</p>
<p>We could also have used a specification for what columns to
include. This can be useful if you have a large number of identifying
columns, and it’s easier to specify what to gather than what to leave
alone. And if the columns are in a row, we don’t even need to list
them all out - just use the <code>:</code> operator!</p>
<div class="sourceCode" id="cb351"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb351-1"><a href="sec-dplyr.html#cb351-1" aria-hidden="true" tabindex="-1"></a>surveys_wide <span class="sc">%&gt;%</span></span>
<span id="cb351-2"><a href="sec-dplyr.html#cb351-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">pivot_longer</span>(<span class="at">names_to =</span> <span class="st">"genus"</span>,</span>
<span id="cb351-3"><a href="sec-dplyr.html#cb351-3" aria-hidden="true" tabindex="-1"></a>                 <span class="at">values_to =</span> <span class="st">"mean_weight"</span>,</span>
<span id="cb351-4"><a href="sec-dplyr.html#cb351-4" aria-hidden="true" tabindex="-1"></a>                 Baiomys<span class="sc">:</span>Spermophilus)</span></code></pre></div>
<pre><code>## # A tibble: 240 x 3
##    plot_id genus           mean_weight
##      &lt;dbl&gt; &lt;chr&gt;                 &lt;dbl&gt;
##  1       1 Baiomys                7   
##  2       1 Chaetodipus           22.2 
##  3       1 Dipodomys             60.2 
##  4       1 Neotoma              156.  
##  5       1 Onychomys             27.7 
##  6       1 Perognathus            9.62
##  7       1 Peromyscus            22.2 
##  8       1 Reithrodontomys       11.4 
##  9       1 Sigmodon              NA   
## 10       1 Spermophilus          NA   
## # … with 230 more rows</code></pre>
<p>To re-arrange the data, we simply pipe le long data to <code>arrange()</code>.</p>
<div class="sourceCode" id="cb353"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb353-1"><a href="sec-dplyr.html#cb353-1" aria-hidden="true" tabindex="-1"></a>surveys_wide <span class="sc">%&gt;%</span></span>
<span id="cb353-2"><a href="sec-dplyr.html#cb353-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">pivot_longer</span>(<span class="at">names_to =</span> <span class="st">"genus"</span>,</span>
<span id="cb353-3"><a href="sec-dplyr.html#cb353-3" aria-hidden="true" tabindex="-1"></a>                 <span class="at">values_to =</span> <span class="st">"mean_weight"</span>,</span>
<span id="cb353-4"><a href="sec-dplyr.html#cb353-4" aria-hidden="true" tabindex="-1"></a>                 Baiomys<span class="sc">:</span>Spermophilus) <span class="sc">%&gt;%</span></span>
<span id="cb353-5"><a href="sec-dplyr.html#cb353-5" aria-hidden="true" tabindex="-1"></a>    <span class="fu">arrange</span>(genus, plot_id)</span></code></pre></div>
<pre><code>## # A tibble: 240 x 3
##    plot_id genus   mean_weight
##      &lt;dbl&gt; &lt;chr&gt;         &lt;dbl&gt;
##  1       1 Baiomys        7   
##  2       2 Baiomys        6   
##  3       3 Baiomys        8.61
##  4       4 Baiomys       NA   
##  5       5 Baiomys        7.75
##  6       6 Baiomys       NA   
##  7       7 Baiomys       NA   
##  8       8 Baiomys       NA   
##  9       9 Baiomys       NA   
## 10      10 Baiomys       NA   
## # … with 230 more rows</code></pre>
<div class="question">
<p class="question-begin">
► Question
</p>
<div class="question-body">
<p>Spread the <code>surveys</code> data frame with <code>year</code> as columns, <code>plot_id</code> as
rows, and the number of genera per plot as the values. You will need
to summarize before reshaping, and use the function <code>n_distinct()</code> to
get the number of unique genera within a particular chunk of
data. It’s a powerful function! See <code>?n_distinct</code> for more.</p>
<p class="question-end">
<span class="fa fa-square-o solution-icon"></span>
</p>
</div>
</div>
<div class="msmb-solution">
<p class="solution-begin">
► Solution<span id="sol-start-22" class="fa fa-plus-square solution-icon clickable" onclick="toggle_visibility('sol-body-22', 'sol-start-22')"></span>
</p>
<div id="sol-body-22" class="solution-body" style="display: none;">
<div class="sourceCode" id="cb355"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb355-1"><a href="sec-dplyr.html#cb355-1" aria-hidden="true" tabindex="-1"></a>rich_time <span class="ot">&lt;-</span> surveys <span class="sc">%&gt;%</span></span>
<span id="cb355-2"><a href="sec-dplyr.html#cb355-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">group_by</span>(plot_id, year) <span class="sc">%&gt;%</span></span>
<span id="cb355-3"><a href="sec-dplyr.html#cb355-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">summarize</span>(<span class="at">n_genera =</span> <span class="fu">n_distinct</span>(genus)) <span class="sc">%&gt;%</span></span>
<span id="cb355-4"><a href="sec-dplyr.html#cb355-4" aria-hidden="true" tabindex="-1"></a>    <span class="fu">pivot_wider</span>(<span class="at">names_from =</span> <span class="st">"year"</span>,</span>
<span id="cb355-5"><a href="sec-dplyr.html#cb355-5" aria-hidden="true" tabindex="-1"></a>                <span class="at">values_from =</span> <span class="st">"n_genera"</span>)</span></code></pre></div>
<pre><code>## `summarise()` has grouped output by 'plot_id'. You can override using the `.groups` argument.</code></pre>
<div class="sourceCode" id="cb357"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb357-1"><a href="sec-dplyr.html#cb357-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(rich_time)</span></code></pre></div>
<pre><code>## # A tibble: 6 x 27
## # Groups:   plot_id [6]
##   plot_id `1977` `1978` `1979` `1980` `1981` `1982` `1983` `1984` `1985` `1986`
##     &lt;dbl&gt;  &lt;int&gt;  &lt;int&gt;  &lt;int&gt;  &lt;int&gt;  &lt;int&gt;  &lt;int&gt;  &lt;int&gt;  &lt;int&gt;  &lt;int&gt;  &lt;int&gt;
## 1       1      2      3      4      7      5      6      7      6      4      3
## 2       2      6      6      6      8      5      9      9      9      6      4
## 3       3      5      6      4      6      6      8     10     11      7      6
## 4       4      4      4      3      4      5      4      6      3      4      3
## 5       5      4      3      2      5      4      6      7      7      3      1
## 6       6      3      4      3      4      5      9      9      7      5      6
## # … with 16 more variables: 1987 &lt;int&gt;, 1988 &lt;int&gt;, 1989 &lt;int&gt;, 1990 &lt;int&gt;,
## #   1991 &lt;int&gt;, 1992 &lt;int&gt;, 1993 &lt;int&gt;, 1994 &lt;int&gt;, 1995 &lt;int&gt;, 1996 &lt;int&gt;,
## #   1997 &lt;int&gt;, 1998 &lt;int&gt;, 1999 &lt;int&gt;, 2000 &lt;int&gt;, 2001 &lt;int&gt;, 2002 &lt;int&gt;</code></pre>
<p class="solution-end">
<span class="fa fa-square-o solution-icon"></span>
</p>
</div>
</div>
<div class="question">
<p class="question-begin">
► Question
</p>
<div class="question-body">
<p>Now take that data frame and transform it with <code>pivot_longer()</code> so
each row is a unique <code>plot_id</code> by <code>year</code> combination.</p>
<p class="question-end">
<span class="fa fa-square-o solution-icon"></span>
</p>
</div>
</div>
<div class="msmb-solution">
<p class="solution-begin">
► Solution<span id="sol-start-23" class="fa fa-plus-square solution-icon clickable" onclick="toggle_visibility('sol-body-23', 'sol-start-23')"></span>
</p>
<div id="sol-body-23" class="solution-body" style="display: none;">
<div class="sourceCode" id="cb359"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb359-1"><a href="sec-dplyr.html#cb359-1" aria-hidden="true" tabindex="-1"></a>rich_time <span class="sc">%&gt;%</span></span>
<span id="cb359-2"><a href="sec-dplyr.html#cb359-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">pivot_longer</span>(<span class="at">names_to =</span> <span class="st">"year"</span>,</span>
<span id="cb359-3"><a href="sec-dplyr.html#cb359-3" aria-hidden="true" tabindex="-1"></a>                 <span class="at">values_to =</span> <span class="st">"n_genera"</span>,</span>
<span id="cb359-4"><a href="sec-dplyr.html#cb359-4" aria-hidden="true" tabindex="-1"></a>                 <span class="sc">-</span>plot_id)</span></code></pre></div>
<pre><code>## # A tibble: 624 x 3
## # Groups:   plot_id [24]
##    plot_id year  n_genera
##      &lt;dbl&gt; &lt;chr&gt;    &lt;int&gt;
##  1       1 1977         2
##  2       1 1978         3
##  3       1 1979         4
##  4       1 1980         7
##  5       1 1981         5
##  6       1 1982         6
##  7       1 1983         7
##  8       1 1984         6
##  9       1 1985         4
## 10       1 1986         3
## # … with 614 more rows</code></pre>
<p class="solution-end">
<span class="fa fa-square-o solution-icon"></span>
</p>
</div>
</div>
<div class="question">
<p class="question-begin">
► Question
</p>
<div class="question-body">
<p>The <code>surveys</code> data set has two measurement columns: <code>hindfoot_length</code>
and <code>weight</code>. This makes it difficult to do things like look at the
relationship between mean values of each measurement per year in
different plot types. Let’s walk through a common solution for this
type of problem. First, use <code>pivot_longer()</code> to create a dataset where
we have a key column called <code>measurement</code> and a <code>value</code> column that
takes on the value of either <code>hindfoot_length</code> or <code>weight</code>.</p>
<p class="question-end">
<span class="fa fa-square-o solution-icon"></span>
</p>
</div>
</div>
<div class="msmb-solution">
<p class="solution-begin">
► Solution<span id="sol-start-24" class="fa fa-plus-square solution-icon clickable" onclick="toggle_visibility('sol-body-24', 'sol-start-24')"></span>
</p>
<div id="sol-body-24" class="solution-body" style="display: none;">
<div class="sourceCode" id="cb361"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb361-1"><a href="sec-dplyr.html#cb361-1" aria-hidden="true" tabindex="-1"></a>surveys_long <span class="ot">&lt;-</span></span>
<span id="cb361-2"><a href="sec-dplyr.html#cb361-2" aria-hidden="true" tabindex="-1"></a>    surveys <span class="sc">%&gt;%</span></span>
<span id="cb361-3"><a href="sec-dplyr.html#cb361-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">pivot_longer</span>(</span>
<span id="cb361-4"><a href="sec-dplyr.html#cb361-4" aria-hidden="true" tabindex="-1"></a>        <span class="at">names_to =</span> <span class="st">"measurement"</span>,</span>
<span id="cb361-5"><a href="sec-dplyr.html#cb361-5" aria-hidden="true" tabindex="-1"></a>        <span class="at">values_to =</span> <span class="st">"value"</span>,</span>
<span id="cb361-6"><a href="sec-dplyr.html#cb361-6" aria-hidden="true" tabindex="-1"></a>        <span class="fu">c</span>(hindfoot_length, weight))</span>
<span id="cb361-7"><a href="sec-dplyr.html#cb361-7" aria-hidden="true" tabindex="-1"></a>surveys_long</span></code></pre></div>
<pre><code>## # A tibble: 69,572 x 13
##    record_id month   day  year plot_id species_id sex   genus   species  taxa  
##        &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;   &lt;dbl&gt; &lt;chr&gt;      &lt;chr&gt; &lt;chr&gt;   &lt;chr&gt;    &lt;chr&gt; 
##  1         1     7    16  1977       2 NL         M     Neotoma albigula Rodent
##  2         1     7    16  1977       2 NL         M     Neotoma albigula Rodent
##  3        72     8    19  1977       2 NL         M     Neotoma albigula Rodent
##  4        72     8    19  1977       2 NL         M     Neotoma albigula Rodent
##  5       224     9    13  1977       2 NL         &lt;NA&gt;  Neotoma albigula Rodent
##  6       224     9    13  1977       2 NL         &lt;NA&gt;  Neotoma albigula Rodent
##  7       266    10    16  1977       2 NL         &lt;NA&gt;  Neotoma albigula Rodent
##  8       266    10    16  1977       2 NL         &lt;NA&gt;  Neotoma albigula Rodent
##  9       349    11    12  1977       2 NL         &lt;NA&gt;  Neotoma albigula Rodent
## 10       349    11    12  1977       2 NL         &lt;NA&gt;  Neotoma albigula Rodent
## # … with 69,562 more rows, and 3 more variables: plot_type &lt;chr&gt;,
## #   measurement &lt;chr&gt;, value &lt;dbl&gt;</code></pre>
<p class="solution-end">
<span class="fa fa-square-o solution-icon"></span>
</p>
</div>
</div>
<div class="question">
<p class="question-begin">
► Question
</p>
<div class="question-body">
<p>With this new data set, calculate the average of each <code>measurement</code> in
each <code>year</code> for each different <code>plot_type</code>. Then use <code>pivot_wider()</code>
to generate a data set with a column for <code>hindfoot_length</code> and
<code>weight</code>.</p>
<p class="question-end">
<span class="fa fa-square-o solution-icon"></span>
</p>
</div>
</div>
<div class="msmb-solution">
<p class="solution-begin">
► Solution<span id="sol-start-25" class="fa fa-plus-square solution-icon clickable" onclick="toggle_visibility('sol-body-25', 'sol-start-25')"></span>
</p>
<div id="sol-body-25" class="solution-body" style="display: none;">
<div class="sourceCode" id="cb363"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb363-1"><a href="sec-dplyr.html#cb363-1" aria-hidden="true" tabindex="-1"></a>surveys_long <span class="sc">%&gt;%</span></span>
<span id="cb363-2"><a href="sec-dplyr.html#cb363-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">group_by</span>(year, measurement, plot_type) <span class="sc">%&gt;%</span></span>
<span id="cb363-3"><a href="sec-dplyr.html#cb363-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">summarize</span>(<span class="at">mean_value =</span> <span class="fu">mean</span>(value, <span class="at">na.rm=</span><span class="cn">TRUE</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb363-4"><a href="sec-dplyr.html#cb363-4" aria-hidden="true" tabindex="-1"></a>    <span class="fu">pivot_wider</span>(<span class="at">names_from =</span> <span class="st">"measurement"</span>,</span>
<span id="cb363-5"><a href="sec-dplyr.html#cb363-5" aria-hidden="true" tabindex="-1"></a>                <span class="at">values_from =</span> <span class="st">"mean_value"</span>)</span></code></pre></div>
<pre><code>## `summarise()` has grouped output by 'year', 'measurement'. You can override using the `.groups` argument.</code></pre>
<pre><code>## # A tibble: 130 x 4
## # Groups:   year [26]
##     year plot_type                 hindfoot_length weight
##    &lt;dbl&gt; &lt;chr&gt;                               &lt;dbl&gt;  &lt;dbl&gt;
##  1  1977 Control                              36.1   50.4
##  2  1977 Long-term Krat Exclosure             33.7   34.8
##  3  1977 Rodent Exclosure                     39.1   48.2
##  4  1977 Short-term Krat Exclosure            35.8   41.3
##  5  1977 Spectab exclosure                    37.2   47.1
##  6  1978 Control                              38.1   70.8
##  7  1978 Long-term Krat Exclosure             22.6   35.9
##  8  1978 Rodent Exclosure                     37.8   67.3
##  9  1978 Short-term Krat Exclosure            36.9   63.8
## 10  1978 Spectab exclosure                    42.3   80.1
## # … with 120 more rows</code></pre>
<p class="solution-end">
<span class="fa fa-square-o solution-icon"></span>
</p>
</div>
</div>
</div>
</div>
<div id="exporting-data-1" class="section level2" number="5.8">
<h2>
<span class="header-section-number">5.8</span> Exporting data<div class="tooltip"><button class="internal-link-btn" onclick="copy_link('exporting-data-1')" onmouseout="reset_tooltip('exporting-data-1-tooltip')"><span class="tooltiptext" id="exporting-data-1-tooltip">Copy link</span><i class="fa fa-link"></i></button></div>
</h2>
<p>Now that you have learned how to use <strong><code>dplyr</code></strong> to extract information from
or summarize your raw data, you may want to export these new data sets to share
them with your collaborators or for archival.</p>
<p>Similar to the <code>read_csv()</code> function used for reading CSV files into R, there is
a <code>write_csv()</code> function that generates CSV files from data frames.</p>
<p>Before using <code>write_csv()</code>, we are going to create a new folder, <code>data_output</code>,
in our working directory that will store this generated dataset. We don’t want
to write generated datasets in the same directory as our raw data. It’s good
practice to keep them separate. The <code>data</code> folder should only contain the raw,
unaltered data, and should be left alone to make sure we don’t delete or modify
it. In contrast, our script will generate the contents of the <code>data_output</code>
directory, so even if the files it contains are deleted, we can always
re-generate them.</p>
<p>In preparation for our next lesson on plotting, we are going to prepare a
cleaned up version of the data set that doesn’t include any missing data.</p>
<p>Let’s start by removing observations of animals for which <code>weight</code> and
<code>hindfoot_length</code> are missing, or the <code>sex</code> has not been determined:</p>
<div class="sourceCode" id="cb366"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb366-1"><a href="sec-dplyr.html#cb366-1" aria-hidden="true" tabindex="-1"></a>surveys_complete <span class="ot">&lt;-</span> surveys <span class="sc">%&gt;%</span></span>
<span id="cb366-2"><a href="sec-dplyr.html#cb366-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="sc">!</span><span class="fu">is.na</span>(weight),           <span class="do">## remove missing weight</span></span>
<span id="cb366-3"><a href="sec-dplyr.html#cb366-3" aria-hidden="true" tabindex="-1"></a>         <span class="sc">!</span><span class="fu">is.na</span>(hindfoot_length),  <span class="do">## remove missing hindfoot_length</span></span>
<span id="cb366-4"><a href="sec-dplyr.html#cb366-4" aria-hidden="true" tabindex="-1"></a>         <span class="sc">!</span><span class="fu">is.na</span>(sex))              <span class="do">## remove missing sex</span></span></code></pre></div>
<p>Because we are interested in plotting how species abundances have changed
through time, we are also going to remove observations for rare species (i.e.,
that have been observed less than 50 times). We will do this in two steps: first
we are going to create a data set that counts how often each species has been
observed, and filter out the rare species; then, we will extract only the
observations for these more common species:</p>
<div class="sourceCode" id="cb367"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb367-1"><a href="sec-dplyr.html#cb367-1" aria-hidden="true" tabindex="-1"></a><span class="do">## Extract the most common species_id</span></span>
<span id="cb367-2"><a href="sec-dplyr.html#cb367-2" aria-hidden="true" tabindex="-1"></a>species_counts <span class="ot">&lt;-</span> surveys_complete <span class="sc">%&gt;%</span></span>
<span id="cb367-3"><a href="sec-dplyr.html#cb367-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">count</span>(species_id) <span class="sc">%&gt;%</span></span>
<span id="cb367-4"><a href="sec-dplyr.html#cb367-4" aria-hidden="true" tabindex="-1"></a>    <span class="fu">filter</span>(n <span class="sc">&gt;=</span> <span class="dv">50</span>)</span>
<span id="cb367-5"><a href="sec-dplyr.html#cb367-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb367-6"><a href="sec-dplyr.html#cb367-6" aria-hidden="true" tabindex="-1"></a><span class="do">## Only keep the most common species</span></span>
<span id="cb367-7"><a href="sec-dplyr.html#cb367-7" aria-hidden="true" tabindex="-1"></a>surveys_complete <span class="ot">&lt;-</span> surveys_complete <span class="sc">%&gt;%</span></span>
<span id="cb367-8"><a href="sec-dplyr.html#cb367-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(species_id <span class="sc">%in%</span> species_counts<span class="sc">$</span>species_id)</span></code></pre></div>
<p>To make sure that everyone has the same data set, check that <code>surveys_complete</code>
has 30463 rows and 13 columns by
typing <code>dim(surveys_complete)</code>.</p>
<p>Now that our data set is ready, we can save it as a CSV file in our <code>data_output</code>
folder.</p>
<div class="sourceCode" id="cb368"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb368-1"><a href="sec-dplyr.html#cb368-1" aria-hidden="true" tabindex="-1"></a><span class="fu">write_csv</span>(surveys_complete, <span class="at">path =</span> <span class="st">"data_output/surveys_complete.csv"</span>)</span></code></pre></div>
<pre><code>## Warning: The `path` argument of `write_csv()` is deprecated as of readr 1.4.0.
## Please use the `file` argument instead.</code></pre>
</div>
<div id="additional-exercises-3" class="section level2" number="5.9">
<h2>
<span class="header-section-number">5.9</span> Additional exercises<div class="tooltip"><button class="internal-link-btn" onclick="copy_link('additional-exercises-3')" onmouseout="reset_tooltip('additional-exercises-3-tooltip')"><span class="tooltiptext" id="additional-exercises-3-tooltip">Copy link</span><i class="fa fa-link"></i></button></div>
</h2>
<div class="question">
<p class="question-begin">
► Question
</p>
<div class="question-body">
<p>We are going to re-analyse beer consumption in 48 individuals using
<code>dplyr</code>. The data are available in the <code>rWSBIM1207</code> package. The data
illustrated the fictive beer consumption in litres per year at
different age according to gender and employment.</p>
<ul>
<li><p>Load the <code>rWSBIM1207</code> package. If the package isn’t installed of its
version is older than 0.1.1, install it from the
<code>UCLouvain-CBIO/rWSBIM1207' GitHub repository using the</code>devtools::install_github` function.</p></li>
<li><p>Directly load the data by typing</p></li>
</ul>
<div class="sourceCode" id="cb370"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb370-1"><a href="sec-dplyr.html#cb370-1" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(beers)</span></code></pre></div>
<ul>
<li><p>Remove observations with missing values.</p></li>
<li><p>Using the <code>Year</code>, <code>Month</code> and <code>Year</code> columns, create a new column
<code>Date</code> using <code>dplyr::mutate</code> and <code>lubridate::ymd</code>. What is the class
of <code>Date</code> ?</p></li>
<li><p>Create a new table, containing observations for women older than 35
years old, employed, and select all columns except Day, Month and
Year, and order in descending value of consumption of beers.</p></li>
<li><p>Export the new table to a <code>csv</code> file.</p></li>
</ul>
<p>Beer consumption analysis:</p>
<ul>
<li>Does employment status have an impact on beer consumption?</li>
<li>Do men drink more than women?</li>
<li>Does employment status have an influence on beer consumption according
to gender?</li>
<li>Do men drink more than women according to age and employment status?</li>
</ul>
<p class="question-end">
<span class="fa fa-square-o solution-icon"></span>
</p>
</div>
</div>
<p>As we can see from the last exercise, it become difficult to read and
interpret multiple results. In the next chapter, we will see how to
complement such analysis questions with visualisations such as the
following one, that clearly highlight important patterns in our data.</p>
<div class="figure" style="text-align: center">
<span id="fig:unnamed-chunk-163"></span>
<p class="caption marginnote shownote">
Figure 5.1: Visualisation of beer consumption, highlighting different patterns of beer consumption in employed and unemployed males and females.
</p>
<img src="figs/ggplot-beer.png" alt="Visualisation of beer consumption, highlighting different patterns of beer consumption in employed and unemployed males and females." width="100%">
</div>
<div class="question">
<p class="question-begin">
► Question
</p>
<div class="question-body">
<p>The Cancer Genome Atlas (TCGA) is a large scale effort that has
collected high throughput biology data from hundreds of patients
samples. In this exercise, we are going to analyse the clinical
variables recorded for a subset of the patients.</p>
<ul>
<li><p>Load the <code>rWSBIM1207</code> package. If the package isn’t installed of its
version is older than 0.1.1, install it from the
<code>UCLouvain-CBIO/rWSBIM1207' GitHub repository using the</code>devtools::install_github` function.</p></li>
<li><p>Using the <code>clinical1.csv()</code> function from <code>rWSBIM1207</code>, find the
path the <code>clinical1.csv</code> file and read it to produce a <code>data.frame</code>
named <code>clinical</code>.</p></li>
<li><p>Familiarise yourself with the data.</p></li>
<li><p>Create a smaller data frame called <code>clinical_mini</code> containing only
the columns corresponding to <code>patientID</code>, <code>gender</code>,
<code>age_at_diagnosis</code>, <code>smoking_history</code>, <code>number_pack_years_smoked</code>,
<code>year_of_tobacco_smoking_onset</code>, and <code>stopped_smoking_year</code>.</p></li>
<li><p>Calculate the number of males and females in the cohort.</p></li>
<li><p>Create a new variable <code>years_at_diagnosis</code> corresponding to the age
at diagnosis converted from days into years.</p></li>
<li><p>Calculate the mean and median age at diagnosis (in years). Pay
attention to missing values!</p></li>
<li><p>Calculate the mean and median age at diagnosis for males and
females.</p></li>
<li><p>How many patient were diagnosed before 50 years?</p></li>
<li><p>Compare the mean age at diagnosis between <em>current smoker</em> and
<em>lifelong non-smoker</em>.</p></li>
<li><p>Select patients who stopped smoking more than 15 years ago and
calculate the number of smoking years for these cases. Display only
cases for which you were able to calculate the data.</p></li>
<li><p>How many of them smoked less than 5 years?</p></li>
<li><p>Try to recreate the following table, reporting the number of smokers
and lifelong-non smoker between males and females. Note: the layout
can be different.</p></li>
</ul>
<table>
<thead><tr class="header">
<th align="left">gender</th>
<th align="right">current smoker</th>
<th align="right">lifelong non-smoker</th>
</tr></thead>
<tbody>
<tr class="odd">
<td align="left">female</td>
<td align="right">51</td>
<td align="right">55</td>
</tr>
<tr class="even">
<td align="left">male</td>
<td align="right">69</td>
<td align="right">20</td>
</tr>
</tbody>
</table>
<p class="question-end">
<span class="fa fa-square-o solution-icon"></span>
</p>
</div>
</div>
<div class="question">
<p class="question-begin">
► Question
</p>
<div class="question-body">
<p>Using the <code>interroA.csv()</code> function from the <code>rWSBIM1207</code> package to
get the path to the spreadsheet file, read the data into R using the
<code>read_csv</code> function. This data is in the wide format, with the results
of each test stored as a separate column.</p>
<p>Using the appropriate pivot function, convert the data into a long
table with a column <code>interro</code> informing which test that line refers to
and a column <code>result</code> with the student’s mark.</p>
<p class="question-end">
<span class="fa fa-square-o solution-icon"></span>
</p>
</div>
</div>

</div>
</div></body></html>

<p style="text-align: center;">
<a href="sec-startdata.html"><button class="btn btn-default">Previous</button></a>
<a href="sec-vis.html"><button class="btn btn-default">Next</button></a>
</p>
<p class="build-date">Page built: 
2021-03-21
 using 
R version 4.0.3 Patched (2021-01-18 r79847)
</p>
</div>
</div>



</body>
</html>
